// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _item.IronAxe = (function(_super) {
    __extends(IronAxe, _super);

    function IronAxe() {
      IronAxe.__super__.constructor.call(this);
      this.name = 'Iron axe';
      this.hit = 75;
      this.might = 8;
      this.weight = 10;
    }

    return IronAxe;

  })(_item.Axe);

  _item.SteelAxe = (function(_super) {
    __extends(SteelAxe, _super);

    function SteelAxe() {
      SteelAxe.__super__.constructor.call(this);
      this.name = 'Steel axe';
      this.image = 'steel_axe.png';
      this.hit = 65;
      this.might = 11;
      this.weight = 13;
      this.uses = _item.uses.steel;
    }

    return SteelAxe;

  })(_item.Axe);

  _item.HandAxe = (function(_super) {
    __extends(HandAxe, _super);

    function HandAxe() {
      HandAxe.__super__.constructor.call(this);
      this.name = 'Hand axe';
      this.image = 'hand_axe.png';
      this.hit = 60;
      this.might = 8;
      this.weight = 8;
      this.uses = 20;
      this.range = new Range(1, 2);
    }

    return HandAxe;

  })(_item.Axe);

}).call(this);
