// Generated by CoffeeScript 1.12.2
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  _item.IronBow = (function(superClass) {
    extend(IronBow, superClass);

    function IronBow() {
      IronBow.__super__.constructor.call(this);
      this.name = 'Iron bow';
      this.hit = 85;
      this.might = 6;
      this.weight = 5;
    }

    return IronBow;

  })(_item.Bow);

  _item.ThrowingKnives = (function(superClass) {
    extend(ThrowingKnives, superClass);

    function ThrowingKnives() {
      ThrowingKnives.__super__.constructor.call(this);
      this.name = 'Throwing knives';
      this.image = '../skills/throwing_knives.png';
      this.range = new Range(1, 2);
    }

    ThrowingKnives.prototype.getMessageEl = function() {
      return _skill.getMessageEl({
        imagePath: 'images/skills/throwing_knives.png',
        text: this.name + '!',
        spanClass: 'small'
      });
    };

    return ThrowingKnives;

  })(_item.IronBow);

  _item.SteelBow = (function(superClass) {
    extend(SteelBow, superClass);

    function SteelBow() {
      SteelBow.__super__.constructor.call(this);
      this.name = 'Steel bow';
      this.image = 'steel_bow.png';
      this.hit = 75;
      this.might = 9;
      this.weight = 5;
      this.uses = _item.uses.steel;
    }

    return SteelBow;

  })(_item.Bow);

  _item.KillerBow = (function(superClass) {
    extend(KillerBow, superClass);

    function KillerBow() {
      KillerBow.__super__.constructor.call(this);
      this.name = 'Killer bow';
      this.image = 'killer_bow.png';
      this.hit = 75;
      this.might = 7;
      this.weight = 7;
      this.crit = 30;
      this.uses = _item.uses.killer;
    }

    return KillerBow;

  })(_item.Bow);

}).call(this);
