// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _item.Shine = (function(_super) {
    __extends(Shine, _super);

    function Shine() {
      Shine.__super__.constructor.call(this);
      this.name = 'Shine';
      this.image = 'shine.png';
      this.hit = 90;
      this.might = 4;
      this.weight = 4;
    }

    return Shine;

  })(_item.Holy);

}).call(this);
