// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window._item = {};

  _item.Item = (function() {
    function Item() {}

    Item.prototype.getElement = function(usable) {
      var el, src;
      if (usable == null) {
        usable = true;
      }
      el = $('<div class="item-element"></div>');
      if (!usable) {
        el.addClass('not-usable');
      }
      src = this.getImagePath();
      el.append($("<img src='" + src + "' />"));
      el.append($("<span>" + this.name + "</span>"));
      el.data('item', this);
      return el;
    };

    Item.prototype.getImagePath = function() {
      return "images/items/" + this.image;
    };

    return Item;

  })();

  _item.Weapon = (function(_super) {
    __extends(Weapon, _super);

    function Weapon() {
      Weapon.__super__.constructor.call(this);
    }

    return Weapon;

  })(_item.Item);

  _item.Sword = (function(_super) {
    __extends(Sword, _super);

    function Sword() {
      this.type = new _skill.type.Sword();
      this.image = 'iron_sword.png';
      this.range = new Range(1);
      Sword.__super__.constructor.call(this);
    }

    return Sword;

  })(_item.Weapon);

  _item.IronSword = (function(_super) {
    __extends(IronSword, _super);

    function IronSword() {
      this.name = 'Iron sword';
      this.hit = 90;
      this.might = 5;
      this.weight = 5;
      this.crit = 0;
      IronSword.__super__.constructor.call(this);
    }

    return IronSword;

  })(_item.Sword);

  _item.Lance = (function(_super) {
    __extends(Lance, _super);

    function Lance() {
      this.type = new _skill.type.Lance();
      this.image = 'iron_lance.png';
      this.range = new Range(1);
      Lance.__super__.constructor.call(this);
    }

    return Lance;

  })(_item.Weapon);

  _item.IronLance = (function(_super) {
    __extends(IronLance, _super);

    function IronLance() {
      this.name = 'Iron lance';
      this.hit = 80;
      this.might = 7;
      this.weight = 8;
      this.crit = 0;
      IronLance.__super__.constructor.call(this);
    }

    return IronLance;

  })(_item.Lance);

  _item.Axe = (function(_super) {
    __extends(Axe, _super);

    function Axe() {
      this.type = new _skill.type.Axe();
      this.image = 'iron_axe.png';
      this.range = new Range(1);
      Axe.__super__.constructor.call(this);
    }

    return Axe;

  })(_item.Weapon);

  _item.IronAxe = (function(_super) {
    __extends(IronAxe, _super);

    function IronAxe() {
      this.name = 'Iron axe';
      this.hit = 75;
      this.might = 8;
      this.weight = 10;
      this.crit = 0;
      IronAxe.__super__.constructor.call(this);
    }

    return IronAxe;

  })(_item.Axe);

  _item.Bow = (function(_super) {
    __extends(Bow, _super);

    function Bow() {
      this.type = new _skill.type.Bow();
      this.image = 'iron_bow.png';
      this.range = new Range(2);
      Bow.__super__.constructor.call(this);
    }

    return Bow;

  })(_item.Weapon);

  _item.IronBow = (function(_super) {
    __extends(IronBow, _super);

    function IronBow() {
      this.name = 'Iron bow';
      this.hit = 85;
      this.might = 6;
      this.weight = 5;
      this.crit = 0;
      IronBow.__super__.constructor.call(this);
    }

    return IronBow;

  })(_item.Bow);

}).call(this);
