// Generated by CoffeeScript 1.12.2
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  _item.IronLance = (function(superClass) {
    extend(IronLance, superClass);

    function IronLance() {
      IronLance.__super__.constructor.call(this);
      this.name = 'Iron lance';
      this.hit = 80;
      this.might = 7;
      this.weight = 8;
    }

    return IronLance;

  })(_item.Lance);

  _item.SteelLance = (function(superClass) {
    extend(SteelLance, superClass);

    function SteelLance() {
      SteelLance.__super__.constructor.call(this);
      this.name = 'Steel lance';
      this.image = 'steel_lance.png';
      this.hit = 70;
      this.might = 10;
      this.weight = 8;
      this.uses = _item.uses.steel;
    }

    return SteelLance;

  })(_item.Lance);

  _item.BraveLance = (function(superClass) {
    extend(BraveLance, superClass);

    function BraveLance() {
      BraveLance.__super__.constructor.call(this);
      this.name = 'Brave lance';
      this.image = 'brave_lance.png';
      this.hit = 80;
      this.might = 7;
      this.weight = 8;
      this.nAttackMultiplier = 2;
      this.uses = _item.uses.brave;
    }

    BraveLance.prototype.hasUses = function(x) {
      return true;
    };

    return BraveLance;

  })(_item.Lance);

}).call(this);
