// Generated by CoffeeScript 1.12.2
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  _item.IronSword = (function(superClass) {
    extend(IronSword, superClass);

    function IronSword() {
      IronSword.__super__.constructor.call(this);
      this.name = 'Iron sword';
      this.hit = 90;
      this.might = 5;
      this.weight = 5;
    }

    return IronSword;

  })(_item.Sword);

  _item.SteelSword = (function(superClass) {
    extend(SteelSword, superClass);

    function SteelSword() {
      SteelSword.__super__.constructor.call(this);
      this.name = 'Steel sword';
      this.image = 'steel_sword.png';
      this.hit = 80;
      this.might = 8;
      this.weight = 5;
      this.uses = _item.uses.steel;
    }

    return SteelSword;

  })(_item.Sword);

}).call(this);
