// Generated by CoffeeScript 1.7.1
(function() {
  window.BattleStatsPanel = (function() {
    function BattleStatsPanel(ui) {
      this.ui = ui;
      this.panel = $('.battle-stats-panel');
    }

    BattleStatsPanel.prototype.init = function(battle) {
      var fillHalf;
      fillHalf = (function(_this) {
        return function(unit, unitName) {
          var statType, td, value, _i, _len, _ref, _results;
          _this.panel.find("." + unitName + "-name").text(unit.name);
          _ref = ['hit', 'dmg', 'crt'];
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            statType = _ref[_i];
            value = unit.battleStats[statType];
            if (value != null) {
              value = Math.round(value);
            } else {
              value = '--';
            }
            td = _this.panel.find("." + unitName + "-" + statType);
            td.find('.stat').text(value);
            if (statType === 'dmg' && battle.nTurns[unitName] === 2) {
              _results.push(td.find('.x2').show());
            } else {
              _results.push(void 0);
            }
          }
          return _results;
        };
      })(this);
      fillHalf(battle.atk, 'atk');
      fillHalf(battle.def, 'def');
      return this.show();
    };

    BattleStatsPanel.prototype.show = function() {
      return this.panel.css('display', 'inline-block');
    };

    BattleStatsPanel.prototype.hide = function() {
      return this.panel.css('display', 'none');
    };

    return BattleStatsPanel;

  })();

}).call(this);
