// Generated by CoffeeScript 1.7.1
(function() {
  var CsEndTurnMenu,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.EndTurnMenu = (function() {
    function EndTurnMenu(ui) {
      this.ui = ui;
      this.menu = $('.end-turn');
    }

    EndTurnMenu.prototype.init = function() {
      var padding;
      padding = 5;
      this.menu.css(this.ui.centerElement(this.menu, padding));
      this.ui.controlState = new CsEndTurnMenu(this.ui, this);
      return this.show();
    };

    EndTurnMenu.prototype.show = function() {
      this.ui.canvasOverlay.show();
      return this.menu.css('visibility', 'visible');
    };

    EndTurnMenu.prototype.hide = function() {
      this.ui.canvasOverlay.hide();
      return this.menu.css('visibility', 'hidden');
    };

    return EndTurnMenu;

  })();

  CsEndTurnMenu = (function(_super) {
    __extends(CsEndTurnMenu, _super);

    function CsEndTurnMenu(ui, menuObj) {
      this.ui = ui;
      this.menuObj = menuObj;
    }

    CsEndTurnMenu.prototype.f = function() {
      var ch;
      this.menuObj.hide();
      ch = this.ui.chapter;
      return ch.initTurn(ch.enemyTeam);
    };

    CsEndTurnMenu.prototype.d = function() {
      this.menuObj.hide();
      return this.ui.controlState = new CsMap(this.ui);
    };

    return CsEndTurnMenu;

  })(ControlState);

}).call(this);
