// Generated by CoffeeScript 1.8.0
(function() {
  var doChapter;

  window.init = function() {
    var ui;
    ui = new _sui.StartUI();
    return ui.init();
  };

  doChapter = function() {
    var file, ui;
    file = _file.createNewFile('normal');
    ui = new _cui.ChapterUI(file);
    ui.setChapter(_chapters.Chapter1);
    return ui.startChapter((function() {}), true);
  };

}).call(this);
