// Generated by CoffeeScript 1.12.2
(function() {
  window.init = function() {
    var file, playerUnits, ui;
    file = {};
    file.difficulty = {
      statBonus: 1,
      expMultiplier: 4 / 3
    };
    playerUnits = [new _unit.special.Ace(), new _unit.special.Arrow(), new _unit.special.Luciana(), new _unit.special.Kenji()];
    file.playerTeam = new _team.PlayerTeam(playerUnits);
    ui = new _chapterui.ChapterUI(file);
    ui.setChapter(_chapters.Chapter1);
    return ui.startChapter(false);
  };

}).call(this);
