// Generated by CoffeeScript 1.7.1
(function() {
  var CsLevelUpWindow,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.LevelUpWindow = (function() {
    function LevelUpWindow(ui) {
      this.ui = ui;
      this.showIncrement = __bind(this.showIncrement, this);
      this.window = $('.level-up-window');
    }

    LevelUpWindow.prototype.init = function(unit, increment, callback) {
      var css, st;
      this.unit = unit;
      this.increment = increment;
      this.callback = callback;
      this.initCommon();
      this.initStats();
      this.ui.controlState = new ControlState(this.ui);
      css = this.ui.centerElement(this.window, 4);
      css.visibility = 'visible';
      this.window.css(css);
      this.incIndex = 0;
      this.incSize = 0;
      for (st in this.increment) {
        this.incSize++;
      }
      this.delay = 750;
      return setTimeout(this.showIncrement, this.delay);
    };

    LevelUpWindow.prototype.initCommon = function() {
      var w;
      this.ui.viewportOverlay.show();
      w = this.window;
      w.find('.common .image-wrapper').removeClass('insignia');
      w.find('.common img').attr('src', 'images/characters/' + this.unit.name.toLowerCase() + '.png');
      w.find('.common .name').html(this.unit.name);
      return w.find('.common .level').text(this.unit.level);
    };

    LevelUpWindow.prototype.initStats = function() {
      var el, st, stats, _i, _len, _ref, _results;
      stats = this.window.find('.stats');
      this.statTypes = ['baseHp', 'str', 'mag', 'def', 'res', 'baseMp', 'skill', 'speed', 'luck', 'move'];
      _ref = this.statTypes;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        st = _ref[_i];
        el = stats.find('.' + st);
        el.find('span').text(this.unit[st]);
        _results.push(el.removeClass('stat-up'));
      }
      return _results;
    };

    LevelUpWindow.prototype.showIncrement = function() {
      var el, st;
      while (true) {
        st = this.statTypes[this.incIndex++];
        if (st in this.increment) {
          break;
        } else if (this.incIndex === this.statTypes.length) {
          this.ui.controlState = new CsLevelUpWindow(this.ui, this);
          return;
        }
      }
      el = this.window.find(".stats ." + st);
      el.find('span').text(this.unit[st] + 1);
      el.addClass('stat-up');
      el.find('img').css('visibility', 'visible');
      this.incIndex++;
      return setTimeout(this.showIncrement, this.delay / 2);
    };

    LevelUpWindow.prototype.hide = function() {
      this.ui.viewportOverlay.hide();
      this.window.css('visibility', 'hidden');
      return this.window.find('.stat img').css('visibility', 'hidden');
    };

    return LevelUpWindow;

  })();

  CsLevelUpWindow = (function(_super) {
    __extends(CsLevelUpWindow, _super);

    function CsLevelUpWindow(ui, windowObj) {
      this.ui = ui;
      this.windowObj = windowObj;
    }

    CsLevelUpWindow.prototype.f = function() {
      return this.d();
    };

    CsLevelUpWindow.prototype.d = function() {
      this.windowObj.hide();
      return this.windowObj.callback();
    };

    return CsLevelUpWindow;

  })(ControlState);

}).call(this);
