// Generated by CoffeeScript 1.7.1
(function() {
  window.MessageBox = (function() {
    function MessageBox(ui) {
      var cpos;
      this.ui = ui;
      this.canvasContainer = $('.canvas-container');
      this.overlay = $('.canvas-dark-overlay');
      cpos = this.ui.canvas.position();
      this.overlay.css({
        top: cpos.top,
        left: cpos.left,
        width: this.ui.canvas.width(),
        height: this.ui.canvas.height()
      });
    }

    MessageBox.prototype.showMessage = function(text, cls, css, callback, callbackArg, doFadeOut) {
      var afterFadeOut, cpos, el, fadeDuration, padding, toDelay;
      el = $(document.createElement('div'));
      el.addClass('message').addClass(cls).text(text);
      this.canvasContainer.append(el);
      cpos = this.ui.canvas.position();
      padding = 10;
      css.top = cpos.top + (this.ui.canvas.height() - el.height()) / 2 - padding;
      css.left = cpos.left + (this.ui.canvas.width() - el.width()) / 2 - padding;
      css.visibility = 'visible';
      css.display = 'none';
      fadeDuration = 800;
      this.overlay.fadeIn(fadeDuration);
      el.css(css).fadeIn(fadeDuration);
      afterFadeOut = (function(_this) {
        return function() {
          return callback(callbackArg);
        };
      })(this);
      toDelay = (function(_this) {
        return function() {
          _this.overlay.fadeOut(fadeDuration);
          return el.fadeOut(fadeDuration, afterFadeOut);
        };
      })(this);
      if (doFadeOut) {
        return setTimeout(toDelay, fadeDuration * 2);
      }
    };

    MessageBox.prototype.showPhaseMessage = function(team, callback) {
      var ch, css, text;
      ch = this.ui.chapter;
      css = {};
      if (team === ch.playerTeam) {
        text = 'Player phase';
        css.color = 'blue';
      } else {
        text = 'Enemy phase';
        css.color = 'red';
      }
      return this.showMessage(text, 'phase-message', css, callback, team, true);
    };

    MessageBox.prototype.showVictoryMessage = function() {
      return this.showMessage('Victory!', 'victory-message', {}, (function() {}), null, false);
    };

    MessageBox.prototype.showDefeatMessage = function() {
      return this.showMessage('Defeat.', 'defeat-message', {}, (function() {}), null, false);
    };

    return MessageBox;

  })();

}).call(this);
