// Generated by CoffeeScript 1.7.1
(function() {
  window.SkillInfoBox = (function() {
    function SkillInfoBox(ui, box) {
      this.ui = ui;
      this.box = box;
    }

    SkillInfoBox.prototype.init = function(skl, usable, full) {
      var desc, heading, usage;
      if (full == null) {
        full = true;
      }
      if (!usable) {
        this.box.addClass('not-usable');
      }
      heading = this.box.find('.heading');
      heading.find('img').attr('src', skl.getImagePath());
      heading.find('span').text(skl.name);
      usage = this.box.find('.usage-container');
      desc = this.box.find('.desc');
      if (full) {
        usage.find('.mp').text(skl.mp);
        usage.show();
        desc.text(skl.desc).show();
      } else {
        usage.hide();
        desc.hide();
      }
      return this.show();
    };

    SkillInfoBox.prototype.show = function() {
      return this.box.css('display', 'block');
    };

    SkillInfoBox.prototype.hide = function() {
      return this.box.css('display', 'none');
    };

    return SkillInfoBox;

  })();

}).call(this);
