// Generated by CoffeeScript 1.7.1
(function() {
  var keydownHandler, keydownHandlerSet,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  keydownHandlerSet = false;

  keydownHandler = function(e) {
    var prevent, _ref;
    switch (e.which) {
      case 38:
        ui.controlState.up();
        break;
      case 40:
        ui.controlState.down();
        break;
      case 37:
        ui.controlState.left();
        break;
      case 39:
        ui.controlState.right();
        break;
      case 70:
        ui.controlState.f();
        break;
      case 68:
        ui.controlState.d();
        break;
      case 83:
        ui.controlState.s();
        break;
      case 69:
        ui.controlState.e();
        break;
      case 86:
        ui.controlState.v();
    }
    prevent = [37, 38, 39, 40];
    if (_ref = e.which, __indexOf.call(prevent, _ref) >= 0) {
      e.preventDefault();
      return false;
    }
  };

  window.UI = (function() {
    function UI() {
      window.ui = this;
      if (!keydownHandlerSet) {
        $(window).keydown(keydownHandler);
        keydownHandlerSet = true;
      }
    }

    return UI;

  })();

}).call(this);
