// Generated by CoffeeScript 1.7.1
(function() {
  window._util = {};

  _util.getFunctionName = function(fun) {
    var s;
    s = fun.toString();
    s = s.substr('function '.length);
    s = s.substr(0, s.indexOf('('));
    return s;
  };

}).call(this);
