// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _turn.PlayerTurn = (function(_super) {
    __extends(PlayerTurn, _super);

    function PlayerTurn(ui) {
      this.ui = ui;
      this.afterExpAdd = __bind(this.afterExpAdd, this);
      this.handleTrade = __bind(this.handleTrade, this);
      this.skillsBoxOnCursorMove = __bind(this.skillsBoxOnCursorMove, this);
      this.skillsBoxOnF = __bind(this.skillsBoxOnF, this);
      this.skillsBoxOnD = __bind(this.skillsBoxOnD, this);
      this.handleSkill = __bind(this.handleSkill, this);
      this.handleAttack = __bind(this.handleAttack, this);
      this.handleItems = __bind(this.handleItems, this);
      this.handleWait = __bind(this.handleWait, this);
      this.initActionMenu = __bind(this.initActionMenu, this);
      this.afterPathFollow = __bind(this.afterPathFollow, this);
      PlayerTurn.__super__.constructor.call(this, this.ui);
      this.tradeRange = new Range(1);
    }

    PlayerTurn.prototype.select = function(unit) {
      var attackRange, spot, _i, _j, _len, _len1, _ref;
      this.available = this.getAvailable(unit);
      attackRange = this.movementGetAttackRange(this.available, unit);
      for (_i = 0, _len = attackRange.length; _i < _len; _i++) {
        spot = attackRange[_i];
        this.ui.chapter.map.setOverlay(spot.targetSpot, 'ATTACK');
      }
      _ref = this.available;
      for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
        spot = _ref[_j];
        this.ui.chapter.map.setOverlay(spot.pos, 'AVAILABLE');
      }
      if (unit.team instanceof _team.PlayerTeam) {
        this.selectedUnit = unit;
        this.dest = new _map.Destination();
        return this.updateDestination();
      } else {
        this.selectedEnemy = unit;
        return this.ui.controlState = new _cs.cui.EnemySelected(this.ui);
      }
    };

    PlayerTurn.prototype.deselect = function() {
      this.selectedUnit = null;
      this.selectedEnemy = null;
      this.dest = null;
      return this.ui.chapter.map.clearOverlay();
    };

    PlayerTurn.prototype.updateDestination = function() {
      var cp, spot, _i, _len, _ref, _results;
      cp = this.ui.cursor.pos;
      if (this.ui.chapter.map.overlayTiles[cp.i][cp.j] === _map.OVERLAY_TYPES.AVAILABLE && (this.selectedUnit != null)) {
        this.dest.pos = cp.clone();
        _ref = this.available;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          spot = _ref[_i];
          if (spot.pos.equals(cp)) {
            this.dest.path = spot.path;
            break;
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      }
    };

    PlayerTurn.prototype.initMove = function() {
      var unitAtDest;
      unitAtDest = this.ui.chapter.getUnitAt(this.dest.pos);
      if (unitAtDest !== null && unitAtDest !== this.selectedUnit) {
        return;
      }
      this.selectedUnit.oldPos = this.selectedUnit.pos;
      this.ui.chapter.map.clearOverlay();
      this.ui.cursor.visible = false;
      this.ui.controlState = new _cs.cui.Chapter(this.ui);
      this.selectedUnit.followPath(this.dest.path, this.afterPathFollow);
      return this.dest = null;
    };

    PlayerTurn.prototype.afterPathFollow = function() {
      this.ui.unitInfoBox.init(this.selectedUnit, false, true);
      this.ui.unitInfoBox.show();
      return this.initActionMenu();
    };

    PlayerTurn.prototype.initActionMenu = function() {
      var actions, attackRange, obj, pos, target, _i, _j, _len, _len1, _ref;
      attackRange = this.getAttackRange(this.selectedUnit, this.selectedUnit.pos);
      this.inAttackRange = [];
      for (_i = 0, _len = attackRange.length; _i < _len; _i++) {
        obj = attackRange[_i];
        target = this.ui.chapter.getUnitAt(obj.targetSpot);
        if ((target != null) && target.team !== this.selectedUnit.team) {
          this.inAttackRange.push(target);
        }
      }
      this.inTradeRange = [];
      _ref = this.getActionRange(this.selectedUnit.pos, this.tradeRange);
      for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
        pos = _ref[_j];
        target = this.ui.chapter.getUnitAt(pos);
        if ((target != null) && target.team === this.selectedUnit.team) {
          this.inTradeRange.push(target);
        }
      }
      actions = [];
      if (this.inAttackRange.length !== 0) {
        actions.push(new _cui.ActionMenuItem('Attack', this.handleAttack));
      }
      actions.push(new _cui.ActionMenuItem('Skill', this.handleSkill));
      if (this.inTradeRange.length !== 0) {
        actions.push(new _cui.ActionMenuItem('Trade', this.handleTrade));
      }
      if (this.selectedUnit.inventory.size() !== 0) {
        actions.push(new _cui.ActionMenuItem('Items', this.handleItems));
      }
      actions.push(new _cui.ActionMenuItem('Wait', this.handleWait));
      return this.ui.actionMenu.init(this.selectedUnit, actions);
    };

    PlayerTurn.prototype.handleWait = function() {
      this.ui.cursor.visible = true;
      this.selectedUnit.setDone();
      return this.deselect();
    };

    PlayerTurn.prototype.handleItems = function() {
      return this.ui.itemMenu.init({
        playerTurn: this
      });
    };

    PlayerTurn.prototype.handleAttack = function() {
      this.ui.actionMenu.hide();
      return this.ui.weaponMenu.init(this);
    };

    PlayerTurn.prototype.handleSkill = function(resetCursor) {
      if (resetCursor == null) {
        resetCursor = true;
      }
      this.ui.skillsBox.resetCursor = resetCursor;
      this.ui.skillsBox.init(this.selectedUnit, this.skillsBoxOnD, this.skillsBoxOnCursorMove);
      this.ui.skillsBox.onF = this.skillsBoxOnF;
      return this.ui.skillsBox.giveControl(resetCursor);
    };

    PlayerTurn.prototype.skillsBoxOnD = function() {
      this.ui.skillsBox.hide();
      return this.ui.actionMenu.init(this.selectedUnit);
    };

    PlayerTurn.prototype.skillsBoxOnF = function() {
      var skill;
      skill = this.ui.skillsBox.getSkill();
      if (!this.selectedUnit.canUseSkill(skill)) {
        return;
      }
      this.ui.skillsBox.hide();
      this.ui.skillInfoBox.init(skill, true, false);
      this.ui.controlState = skill.getControlState(this.ui, this);
      return this.ui.cursor.visible = true;
    };

    PlayerTurn.prototype.skillsBoxOnCursorMove = function() {
      var skill;
      skill = this.ui.skillsBox.getSkill();
      if (this.selectedUnit.mp < skill.mp) {
        return this.ui.chapter.map.clearOverlay();
      } else {
        return this.ui.chapter.map.setOverlayRange(this.selectedUnit.pos, skill.range, skill.overlayType);
      }
    };

    PlayerTurn.prototype.handleTrade = function() {
      this.ui.chapter.map.setOverlayRange(this.selectedUnit.pos, this.tradeRange, 'AID');
      this.ui.controlState = new _cs.cui.ChooseTradeTarget(this.ui, this);
      this.ui.cursor.visible = true;
      return this.ui.cursor.moveTo(this.inTradeRange[0].pos);
    };

    PlayerTurn.prototype.afterExpAdd = function() {
      this.ui.controlState = new _cs.cui.Map(this.ui);
      this.ui.cursor.visible = true;
      this.ui.cursor.moveTo(this.selectedUnit.pos);
      this.selectedUnit.setDone();
      return this.selectedUnit = null;
    };

    return PlayerTurn;

  })(_turn.Turn);

}).call(this);
