// Generated by CoffeeScript 1.8.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _enc.AidEncounter = (function(_super) {
    __extends(AidEncounter, _super);

    function AidEncounter() {
      this.doAction = __bind(this.doAction, this);
      return AidEncounter.__super__.constructor.apply(this, arguments);
    }

    AidEncounter.prototype.doEncounter = function(callback, skill, delta) {
      this.callback = callback;
      this.skill = skill;
      this.delta = delta;
      return AidEncounter.__super__.doEncounter.call(this, this.callback);
    };

    AidEncounter.prototype.doAction = function() {
      var afterDelay, afterFadeIn, message;
      this.atk.mp -= this.skill.mp;
      if ('hp' in this.delta) {
        this.def.addHp(this.delta.hp);
      }
      message = this.skill.getMessageEl();
      message.addClass('blue-box').appendTo(this.container);
      afterFadeIn = (function(_this) {
        return function() {
          _this.doLunge(_this.atk);
          _this.atkBox.init(_this.atk, true);
          _this.defBox.init(_this.def, true);
          return setTimeout(afterDelay, _this.delay * 4 / 3);
        };
      })(this);
      afterDelay = (function(_this) {
        return function() {
          _this.container.fadeOut(_this.delay / 3);
          return message.fadeOut(_this.delay / 3, _this.encounterDone);
        };
      })(this);
      return message.fadeIn(this.delay / 3, afterFadeIn);
    };

    return AidEncounter;

  })(_enc.Encounter);

}).call(this);
