// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window._chapters = {};

  _chapters.Chapter1 = (function(_super) {
    __extends(Chapter1, _super);

    function Chapter1(ui) {
      var enemyUnits, map, playerPositions, playerUnits, terrainMapping, tiles;
      this.ui = ui;
      playerUnits = [new _uclass.special.Ace(), new _uclass.special.Arrow(), new _uclass.special.Luciana(), new _uclass.special.Kenji()];
      this.playerTeam = new _team.PlayerTeam(playerUnits);
      enemyUnits = [
        new _uclass.Fighter({
          pos: new Position(4, 2),
          level: 1,
          inventory: [new _item.IronAxe()]
        }), new _uclass.Fighter({
          pos: new Position(5, 4),
          level: 1,
          inventory: [new _item.IronAxe()]
        }), new _uclass.Archer({
          pos: new Position(8, 3),
          level: 1,
          inventory: [new _item.IronBow()]
        }), new _uclass.Soldier({
          pos: new Position(6, 5),
          level: 2,
          aiType: _unit.AI_TYPE.HALT,
          inventory: [new _item.IronLance()]
        }), new _uclass.Soldier({
          pos: new Position(7, 5),
          level: 2,
          aiType: _unit.AI_TYPE.HALT,
          inventory: [new _item.IronLance()]
        }), new _uclass.Mercenary({
          pos: new Position(7, 8),
          level: 1,
          inventory: [new _item.IronSword()]
        }), new _uclass.Fighter({
          pos: new Position(6, 7),
          level: 1,
          inventory: [new _item.IronAxe()]
        }), new _uclass.Archer({
          pos: new Position(6, 15),
          level: 1,
          aiType: _unit.AI_TYPE.HALT,
          inventory: [new _item.IronBow()]
        }), new _uclass.Archer({
          pos: new Position(7, 14),
          level: 1,
          inventory: [new _item.IronBow()]
        }), new _uclass.Fighter({
          pos: new Position(1, 8),
          level: 1,
          inventory: [new _item.IronAxe()]
        }), new _uclass.Fighter({
          pos: new Position(3, 10),
          level: 1,
          inventory: [new _item.IronAxe()]
        }), new _uclass.Mercenary({
          pos: new Position(3, 12),
          level: 1,
          inventory: [new _item.IronSword()]
        }), new _uclass.Mercenary({
          pos: new Position(6, 12),
          level: 1,
          inventory: [new _item.IronSword()]
        }), new _uclass.Fighter({
          pos: new Position(3, 15),
          aiType: _unit.AI_TYPE.HALT,
          boss: true,
          level: 5,
          inventory: [new _item.IronAxe()]
        })
      ];
      this.enemyTeam = new _team.EnemyTeam(enemyUnits, {
        defaultName: 'Bandit'
      });
      this.enemyTeam.insigniaImagePath = 'images/bandit_insignia.png';
      terrainMapping = {
        0: _terrain.Plain,
        1: _terrain.Rocks,
        2: _terrain.Forest
      };
      tiles = [[0, 0, 0, 2, 2, 1, 1, 2, 2, 1, 1, 1, 0, 2, 1, 1], [0, 0, 0, 0, 2, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 2, 1, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 2, 0, 0, 2], [0, 0, 0, 2, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0], [0, 0, 2, 0, 0, 1, 0, 0, 0, 2, 1, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2], [0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 1], [1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 2, 2, 2], [1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 1, 1, 2, 1, 1, 1]];
      playerPositions = [[2, 1], [1, 0], [0, 1], [1, 2]];
      this.origin0 = new Position(0, 4 * this.ui.tw);
      this.victoryCondition = _map.VICTORY_CONDITION.ROUT;
      map = new _map.Map(tiles, terrainMapping, playerPositions);
      Chapter1.__super__.constructor.call(this, this.ui, map);
    }

    Chapter1.prototype.doScrollSequence = function(callback) {
      var f;
      f = (function(_this) {
        return function() {
          return _this.ui.scrollTo(new Position(0, 0), callback, .07);
        };
      })(this);
      return setTimeout(f, 1000 / this.ui.speedMultiplier);
    };

    return Chapter1;

  })(_map.Chapter);

}).call(this);
