// Generated by CoffeeScript 1.7.1
(function() {
  _cui.BattleStatsPanel = (function() {
    function BattleStatsPanel(ui) {
      this.ui = ui;
      this.panel = $('.battle-stats-panel');
    }

    BattleStatsPanel.prototype.init = function(battle) {
      var fillHalf;
      fillHalf = (function(_this) {
        return function(unit, unitName) {
          var img, imgSrc, nameCell, statType, td, value, _i, _len, _ref, _results;
          nameCell = _this.panel.find("." + unitName + "-name");
          nameCell.find('span').text(unit.name);
          imgSrc = unit.equipped.getImagePath();
          nameCell.find('img.weapon').attr('src', imgSrc);
          if (unit.advantage === true) {
            imgSrc = "images/up_arrow.png";
          } else if (unit.advantage === false) {
            imgSrc = "images/down_arrow.png";
          } else {
            imgSrc = null;
          }
          img = nameCell.find('img.weapon-arrow');
          if (imgSrc != null) {
            img.attr('src', imgSrc).show();
          } else {
            img.hide();
          }
          _ref = ['hp', 'hit', 'dmg', 'crt'];
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            statType = _ref[_i];
            if (statType === 'hp') {
              value = unit.hp;
            } else {
              value = unit.battleStats[statType];
            }
            if (value != null) {
              value = Math.round(value);
            } else {
              value = '--';
            }
            td = _this.panel.find("." + unitName + "-" + statType);
            td.find('.stat').text(value);
            if (statType === 'dmg' && battle.nTurns[unitName] === 2) {
              _results.push(td.find('.x2').show());
            } else {
              _results.push(td.find('.x2').hide());
            }
          }
          return _results;
        };
      })(this);
      fillHalf(battle.atk, 'atk');
      fillHalf(battle.def, 'def');
      return this.show();
    };

    BattleStatsPanel.prototype.show = function() {
      return this.panel.css('display', 'inline-block');
    };

    BattleStatsPanel.prototype.hide = function() {
      return this.panel.css('display', 'none');
    };

    return BattleStatsPanel;

  })();

}).call(this);
