// Generated by CoffeeScript 1.8.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window._cui = {};

  _cs.cui = {};

  _cui.ChapterUI = (function(_super) {
    __extends(ChapterUI, _super);

    ChapterUI.prototype.tw = 35;

    function ChapterUI(file) {
      var skillInfoBoxEl, skillsBoxEl;
      this.file = file;
      this.mainLoop = __bind(this.mainLoop, this);
      this.doneDefeat = __bind(this.doneDefeat, this);
      this.doneVictory = __bind(this.doneVictory, this);
      ChapterUI.__super__.constructor.call(this);
      this.setConfirmUnload(true);
      this.expMultiplier = this.file.difficulty.expMultiplier;
      this.speedMultiplier = 1;
      this.fadeDelay = 1000;
      this.gameWrapper = $('.game-wrapper');
      this.then = Date.now();
      this.canvas = $('canvas');
      this.ctx = this.canvas[0].getContext('2d');
      this.canvasDim = new Position(10, 12);
      this.cursor = new _cui.Cursor(this);
      this.controlState = new _cs.cui.Chapter(this);
      this.actionMenu = new _cui.ActionMenuMain(this);
      this.weaponMenu = new _cui.WeaponMenu(this);
      this.itemMenu = new _cui.ItemMenu(this);
      this.battleStatsPanel = new _cui.BattleStatsPanel(this);
      this.expBar = new _cui.ExpBar(this);
      skillInfoBoxEl = $('.sidebar .skill-info-box');
      skillInfoBoxEl.clone().appendTo($('.canvas-container'));
      this.skillInfoBox = new _cui.SkillInfoBox(this, skillInfoBoxEl);
      skillsBoxEl = $('.sidebar .skills-box');
      skillsBoxEl.addClass('neutral-box');
      this.skillsBox = new _cui.SkillsBox(this, skillsBoxEl, this.skillInfoBox);
      this.unitInfoBox = new _cui.UnitInfoBox(this, '.sidebar .unit-info');
      this.unitInfoWindow = new _cui.UnitInfoWindow(this);
      this.levelUpWindow = new _cui.LevelUpWindow(this);
      this.tradeWindow = new _cui.TradeWindow(this);
      this.canvasOverlay = new _cui.CanvasOverlay(this);
      this.viewportOverlay = new _cui.ViewportOverlay(this);
      this.messageBox = new _cui.MessageBox(this);
      this.endTurnMenu = new _cui.EndTurnMenu(this);
      this.terrainBox = new _cui.TerrainBox(this);
      this.speedMultiplierBox = $('.speed-multiplier-box').hide();
      this.staticTurn = new _turn.Turn(this);
    }

    ChapterUI.prototype.setChapter = function(chapterCls) {
      this.chapter = new chapterCls(this);
      this.chapter.setPlayerTeam(this.file.playerTeam);
      $('.victory-condition').text(this.chapter.victoryCondition.text).show();
      this.origin = this.chapter.origin0;
      return this.mainLoop();
    };

    ChapterUI.prototype.startChapter = function(callback, devMode) {
      var afterFade, afterScroll;
      this.callback = callback;
      if (devMode == null) {
        devMode = false;
      }
      afterFade = (function(_this) {
        return function() {
          return _this.chapter.doScrollSequence(afterScroll);
        };
      })(this);
      afterScroll = (function(_this) {
        return function() {
          return _this.chapter.initTurn(_this.chapter.playerTeam);
        };
      })(this);
      if (!devMode) {
        return this.gameWrapper.fadeIn(this.fadeDelay, afterFade);
      } else {
        this.gameWrapper.show();
        this.origin = new Position(0, 0);
        return afterScroll();
      }
    };

    ChapterUI.prototype.doneVictory = function() {
      return this.destroy(this.callback);
    };

    ChapterUI.prototype.doneDefeat = function() {
      var callback;
      callback = (function(_this) {
        return function() {
          var ui;
          ui = new _sui.StartUI();
          return ui.init({
            fade: true
          });
        };
      })(this);
      return this.destroy(callback);
    };

    ChapterUI.prototype.destroy = function(callback) {
      return this.gameWrapper.fadeOut(this.fadeDelay, callback);
    };

    ChapterUI.prototype.onScreen = function(pos) {
      var delta, _ref, _ref1;
      delta = pos.scale(this.tw).subtract(this.origin);
      return (0 <= (_ref = delta.i) && _ref < this.canvas.height()) && (0 <= (_ref1 = delta.j) && _ref1 < this.canvas.width());
    };

    ChapterUI.prototype.scrollTo = function(pos, scrollCallback, scrollSpeed) {
      var centerOffset, map, maxI, maxJ;
      this.scrollCallback = scrollCallback;
      this.scrollSpeed = scrollSpeed != null ? scrollSpeed : null;
      centerOffset = new Position(5, 6);
      this.scrollDest = pos.subtract(centerOffset);
      map = this.chapter.map;
      maxI = map.height - this.canvasDim.i;
      if (this.scrollDest.i < 0) {
        this.scrollDest.i = 0;
      } else if (this.scrollDest.i > maxI) {
        this.scrollDest.i = maxI;
      }
      maxJ = map.width - this.canvasDim.j;
      if (this.scrollDest.j < 0) {
        this.scrollDest.j = 0;
      } else if (this.scrollDest.j > maxJ) {
        this.scrollDest.j = maxJ;
      }
      this.direction = this.scrollDest.scale(this.tw).subtract(this.origin);
      if (!this.direction.equals(new Position(0, 0))) {
        this.direction = this.direction.toUnitVector();
        if (this.scrollSpeed == null) {
          return this.scrollSpeed = .2;
        }
      } else {
        return this.direction = null;
      }
    };

    ChapterUI.prototype.centerElement = function(el, padding) {
      var css;
      css = {};
      css.top = (this.canvas.height() - el.height()) / 2 - padding;
      css.left = (this.canvas.width() - el.width()) / 2 - padding;
      return css;
    };

    ChapterUI.prototype.render = function() {
      if (this.chapter != null) {
        this.chapter.render(this, this.ctx);
      }
      return this.cursor.render(this, this.ctx);
    };

    ChapterUI.prototype.update = function(delta) {
      var alt, unit, _i, _len, _ref, _results;
      delta *= this.speedMultiplier;
      if (this.direction != null) {
        this.origin = this.origin.add(this.direction.scale(delta * this.scrollSpeed));
        alt = this.scrollDest.scale(this.tw).subtract(this.origin);
        if (alt.dot(this.direction) <= 0) {
          this.origin = this.scrollDest.scale(this.tw);
          this.direction = null;
          if (this.scrollCallback != null) {
            this.scrollCallback();
          }
        }
      }
      _ref = this.chapter.units;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        unit = _ref[_i];
        unit.updateLunge();
        if (unit.direction != null) {
          if (unit.followingPath && (Math.abs(unit.offset.i) >= this.tw || Math.abs(unit.offset.j) >= this.tw)) {
            _results.push(unit.pathNext());
          } else {
            _results.push(unit.offset = unit.offset.add(unit.direction.scale(delta * unit.movementSpeed)));
          }
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    ChapterUI.prototype.mainLoop = function() {
      var delta, now;
      now = Date.now();
      delta = now - this.then;
      this.then = now;
      this.update(delta);
      requestAnimationFrame(this.mainLoop);
      return this.render();
    };

    return ChapterUI;

  })(UI);

  _cs.cui.Chapter = (function(_super) {
    __extends(Chapter, _super);

    function Chapter(ui) {
      this.ui = ui;
      this.v = __bind(this.v, this);
    }

    Chapter.prototype.up = function() {};

    Chapter.prototype.down = function() {};

    Chapter.prototype.left = function() {};

    Chapter.prototype.right = function() {};

    Chapter.prototype.f = function() {};

    Chapter.prototype.d = function() {};

    Chapter.prototype.s = function() {};

    Chapter.prototype.e = function() {};

    Chapter.prototype.v = function() {
      if (this.ui.speedMultiplier === 3) {
        this.ui.speedMultiplier = 1;
        return this.ui.speedMultiplierBox.hide();
      } else {
        this.ui.speedMultiplier = 3;
        return this.ui.speedMultiplierBox.show();
      }
    };

    return Chapter;

  })(_cs.ControlState);

}).call(this);
