// Generated by CoffeeScript 1.7.1
(function() {
  _cui.Cursor = (function() {
    function Cursor(ui) {
      this.ui = ui;
      this.visible = false;
    }

    Cursor.prototype.moveTo = function(pos) {
      this.pos = pos.clone();
      this.ui.chapter.playerTurn.updateDestination();
      this.ui.unitInfoBox.update();
      this.ui.terrainBox.init();
      if (this.ui.controlState.moved != null) {
        return this.ui.controlState.moved();
      }
    };

    Cursor.prototype.move = function(di, dj) {
      var c, newPos, newPosPx;
      newPos = this.pos.add(new Position(di, dj));
      newPosPx = newPos.scale(this.ui.tw);
      c = this.ui.canvas;
      if (newPosPx.j >= c.width() + this.ui.origin.j || newPosPx.j < this.ui.origin.j) {
        this.ui.origin.j += dj * this.ui.tw;
      }
      if (newPosPx.i >= c.height() + this.ui.origin.i || newPosPx.i < this.ui.origin.i) {
        this.ui.origin.i += di * this.ui.tw;
      }
      return this.moveTo(newPos);
    };

    Cursor.prototype.render = function(ui, ctx) {
      var s, tw;
      if (!this.visible || (this.pos == null)) {
        return;
      }
      s = 5;
      tw = ui.tw;
      ctx.strokeStyle = 'purple';
      ctx.beginPath();
      ctx.rect(this.pos.j * tw + s - ui.origin.j, this.pos.i * tw + s - ui.origin.i, tw - 2 * s, tw - 2 * s);
      return ctx.stroke();
    };

    return Cursor;

  })();

}).call(this);
