// Generated by CoffeeScript 1.7.1
(function() {
  var HEIGHT, WIDTH,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  WIDTH = 4;

  HEIGHT = 4;

  _cui.SkillsBox = (function() {
    function SkillsBox(ui, box, skillInfoBox) {
      this.ui = ui;
      this.box = box;
      this.skillInfoBox = skillInfoBox;
    }

    SkillsBox.prototype.init = function(unit, onD, onCursorMove) {
      var i, img, skl, td, tr, _i, _ref;
      this.unit = unit;
      this.onD = onD;
      this.onCursorMove = onCursorMove;
      this.box.html('');
      for (i = _i = 0, _ref = this.unit.skills.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        if (i % WIDTH === 0) {
          tr = $('<tr></tr>').appendTo(this.box);
        }
        td = $('<td></td>').appendTo(tr);
        td.addClass('skill');
        skl = this.unit.skills[i];
        img = $('<img />').attr('src', skl.getImagePath()).appendTo(td);
        td.data('skill', skl);
      }
      i %= WIDTH;
      while (i < WIDTH) {
        $('<td></td>').appendTo(tr);
        i++;
      }
      return this.show();
    };

    SkillsBox.prototype.giveControl = function(resetCursor) {
      var pos;
      if (resetCursor == null) {
        resetCursor = true;
      }
      if (resetCursor) {
        pos = new Position(0, 0);
      } else {
        pos = this.cursorPos;
      }
      this.setCursorPos(pos);
      return this.ui.controlState = new _cs.cui.SkillsBox(this.ui, this);
    };

    SkillsBox.prototype.getSkill = function() {
      return this.getCursorCell().data('skill');
    };

    SkillsBox.prototype.getCell = function(pos) {
      var row;
      row = $(this.box.find('tr')[pos.i]);
      return $(row.find('td')[pos.j]);
    };

    SkillsBox.prototype.getCursorCell = function() {
      return this.getCell(this.cursorPos);
    };

    SkillsBox.prototype.setCursorPos = function(cursorPos) {
      this.cursorPos = cursorPos;
      if (this.onCursorMove != null) {
        this.onCursorMove();
      }
      this.box.find('.selected').removeClass('selected');
      this.getCursorCell().addClass('selected');
      return this.updateInfoBox();
    };

    SkillsBox.prototype.updateInfoBox = function() {
      var skl;
      skl = this.getSkill();
      return this.skillInfoBox.init(skl, this.unit.canUseSkill(skl));
    };

    SkillsBox.prototype.show = function() {
      return this.box.css('display', 'block');
    };

    SkillsBox.prototype.hide = function() {
      return this.box.css('display', 'none');
    };

    return SkillsBox;

  })();

  _cs.cui.SkillsBox = (function(_super) {
    __extends(SkillsBox, _super);

    function SkillsBox(ui, boxObj) {
      this.ui = ui;
      this.boxObj = boxObj;
    }

    SkillsBox.prototype.skillAt = function(cp) {
      return this.boxObj.getCell(cp).hasClass('skill');
    };

    SkillsBox.prototype.f = function() {
      return this.boxObj.onF();
    };

    SkillsBox.prototype.d = function() {
      this.boxObj.box.find('.selected').removeClass('selected');
      this.boxObj.skillInfoBox.hide();
      return this.boxObj.onD();
    };

    SkillsBox.prototype.left = function() {
      var cp, cp1, j, _i, _ref, _results;
      cp = this.boxObj.cursorPos;
      if (cp.j > 0) {
        cp1 = new Position(cp.i, cp.j - 1);
        return this.boxObj.setCursorPos(cp1);
      } else {
        _results = [];
        for (j = _i = _ref = WIDTH - 1; _ref <= 0 ? _i <= 0 : _i >= 0; j = _ref <= 0 ? ++_i : --_i) {
          cp1 = new Position(cp.i, j);
          if (this.skillAt(cp1)) {
            this.boxObj.setCursorPos(cp1);
            break;
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      }
    };

    SkillsBox.prototype.right = function() {
      var cp, cp1;
      cp = this.boxObj.cursorPos;
      cp1 = new Position(cp.i, cp.j + 1);
      if (!(cp.j + 1 < WIDTH && this.skillAt(cp1))) {
        cp1 = new Position(cp.i, 0);
      }
      return this.boxObj.setCursorPos(cp1);
    };

    SkillsBox.prototype.up = function() {
      var cp, cp1, i, _i, _ref, _results;
      cp = this.boxObj.cursorPos;
      if (cp.i > 0) {
        cp1 = new Position(cp.i - 1, cp.j);
        return this.boxObj.setCursorPos(cp1);
      } else {
        _results = [];
        for (i = _i = _ref = WIDTH - 1; _ref <= 0 ? _i <= 0 : _i >= 0; i = _ref <= 0 ? ++_i : --_i) {
          cp1 = new Position(i, cp.j);
          if (this.skillAt(cp1)) {
            this.boxObj.setCursorPos(cp1);
            break;
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      }
    };

    SkillsBox.prototype.down = function() {
      var cp, cp1;
      cp = this.boxObj.cursorPos;
      cp1 = new Position(cp.i + 1, cp.j);
      if (!(cp1.i < HEIGHT && this.skillAt(cp1))) {
        cp1 = new Position(0, cp.j);
      }
      return this.boxObj.setCursorPos(cp1);
    };

    return SkillsBox;

  })(_cs.cui.Chapter);

}).call(this);
