// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _cui.WeaponMenu = (function() {
    function WeaponMenu(ui) {
      var itemInfoBoxEl;
      this.ui = ui;
      this.menu = $('.weapon-menu');
      itemInfoBoxEl = $('.sidebar .item-info-box');
      this.itemInfoBox = new _cui.ItemInfoBox(this.ui, itemInfoBoxEl);
    }

    WeaponMenu.prototype.init = function(playerTurn) {
      var item, menuItem, options, _i, _len, _ref;
      if (playerTurn != null) {
        this.playerTurn = playerTurn;
        this.unit = this.playerTurn.selectedUnit;
      }
      this.menu.html('');
      _ref = this.unit.inventory.it();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        if (this.unit.canWield(item)) {
          options = {
            equipped: item === this.unit.equipped
          };
          menuItem = $('<div><div class="image"></div></div>');
          menuItem.addClass('menu-choice');
          menuItem.append(item.getElement(options));
          menuItem.appendTo(this.menu);
        }
      }
      this.menu.children('div').first().addClass('selected');
      this.selectedItemChanged();
      this.show();
      return this.ui.controlState = new _cs.cui.WeaponMenu(this.ui, this);
    };

    WeaponMenu.prototype.getSelectedItem = function() {
      var el;
      el = this.menu.find('.selected .item-element');
      return el.data('item');
    };

    WeaponMenu.prototype.selectedItemChanged = function() {
      var item;
      item = this.getSelectedItem();
      return this.itemInfoBox.init(item, this.unit.canUse(item));
    };

    WeaponMenu.prototype.show = function() {
      return this.menu.css('display', 'inline-block');
    };

    WeaponMenu.prototype.hide = function() {
      this.itemInfoBox.hide();
      return this.menu.css('display', 'none');
    };

    return WeaponMenu;

  })();

  _cs.cui.WeaponMenu = (function(_super) {
    __extends(WeaponMenu, _super);

    function WeaponMenu(ui, menuObj) {
      this.ui = ui;
      this.menuObj = menuObj;
      this.playerTurn = this.ui.chapter.playerTurn;
    }

    WeaponMenu.prototype.onChange = function() {
      return this.menuObj.selectedItemChanged();
    };

    WeaponMenu.prototype.f = function() {
      var item, pt;
      item = this.menuObj.getSelectedItem();
      this.menuObj.unit.setEquipped(item);
      this.ui.weaponMenu.hide();
      pt = this.menuObj.playerTurn;
      this.ui.controlState = new _cs.cui.ChooseAttackTarget(this.ui, pt);
      this.ui.cursor.moveTo(pt.inAttackRange[0].pos);
      return this.ui.cursor.visible = true;
    };

    WeaponMenu.prototype.d = function() {
      this.menuObj.hide();
      return this.ui.actionMenu.init();
    };

    return WeaponMenu;

  })(_cs.cui.Menu);

}).call(this);
