// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _file.fs.Chapter1 = (function(_super) {
    __extends(Chapter1, _super);

    function Chapter1() {
      return Chapter1.__super__.constructor.apply(this, arguments);
    }

    Chapter1.prototype.init = function() {
      var lines;
      this.ui = new _vn.VisualNovelUI();
      lines = ['Here is some text', 'Here is the second line'];
      return this.ui.fullTextbox.init(lines, this.doChapter);
    };

    Chapter1.prototype.doChapter = function() {
      this.ui.destroy();
      this.ui = new _cui.ChapterUI();
      this.ui.setChapter(_chapters.Chapter1);
      return this.ui.startChapter();
    };

    return Chapter1;

  })(_file.FileState);

}).call(this);
