// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window._file = {};

  _file.difficulty = {
    normal: {},
    hard: {}
  };

  _file.File = (function() {
    function File() {}

    File.prototype.init = function() {
      return this.fileState.init();
    };

    return File;

  })();

  _file.fs = {};

  _file.FileState = (function() {
    function FileState() {}

    return FileState;

  })();

  _file.fs.Prologue = (function(_super) {
    __extends(Prologue, _super);

    function Prologue() {
      return Prologue.__super__.constructor.apply(this, arguments);
    }

    return Prologue;

  })(_file.FileState);

  _file.fs.Chapter1 = (function(_super) {
    __extends(Chapter1, _super);

    function Chapter1() {
      return Chapter1.__super__.constructor.apply(this, arguments);
    }

    Chapter1.prototype.init = function() {
      var ui;
      ui = new _cui.ChapterUI();
      ui.setChapter(new _chapters.Chapter1(ui));
      return ui.startChapter();
    };

    return Chapter1;

  })(_file.FileState);

}).call(this);
