// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.item = {};

  item.Item = (function() {
    function Item() {}

    Item.prototype.getElement = function() {
      var el, src;
      el = $('<div class="weapon-element"></div>');
      src = "images/items/" + this.image;
      el.append($("<img src='" + src + "' />"));
      el.append($("<span>" + this.name + "</span>"));
      return el;
    };

    return Item;

  })();

  item.Weapon = (function(_super) {
    __extends(Weapon, _super);

    function Weapon() {
      Weapon.__super__.constructor.call(this);
    }

    return Weapon;

  })(item.Item);

  item.Sword = (function(_super) {
    __extends(Sword, _super);

    function Sword() {
      this.image = 'iron_sword.png';
      this.range = [1];
      Sword.__super__.constructor.call(this);
    }

    return Sword;

  })(item.Weapon);

  item.IronSword = (function(_super) {
    __extends(IronSword, _super);

    function IronSword() {
      this.name = 'Iron sword';
      this.hit = 85;
      this.might = 4;
      this.weight = 2;
      this.crit = 0;
      IronSword.__super__.constructor.call(this);
    }

    return IronSword;

  })(item.Sword);

  item.Bow = (function(_super) {
    __extends(Bow, _super);

    function Bow() {
      this.image = 'iron_bow.png';
      this.range = [2];
      Bow.__super__.constructor.call(this);
    }

    return Bow;

  })(item.Weapon);

  item.IronBow = (function(_super) {
    __extends(IronBow, _super);

    function IronBow() {
      this.name = 'Iron bow';
      this.hit = 85;
      this.might = 4;
      this.weight = 2;
      this.crit = 0;
      IronBow.__super__.constructor.call(this);
    }

    return IronBow;

  })(item.Bow);

}).call(this);
