// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.item = {};

  item.Item = (function() {
    function Item() {}

    Item.prototype.getElement = function() {
      var el, src;
      el = $('<div class="weapon-element"></div>');
      src = "images/items/" + this.image;
      el.append($("<img src='" + src + "' />"));
      el.append($("<span>" + this.name + "</span>"));
      return el;
    };

    return Item;

  })();

  item.Weapon = (function(_super) {
    __extends(Weapon, _super);

    function Weapon() {
      Weapon.__super__.constructor.call(this);
    }

    return Weapon;

  })(item.Item);

  item.Sword = (function(_super) {
    __extends(Sword, _super);

    function Sword() {
      this.image = 'iron_sword.png';
      this.range = [1];
      Sword.__super__.constructor.call(this);
    }

    return Sword;

  })(item.Weapon);

  item.IronSword = (function(_super) {
    __extends(IronSword, _super);

    function IronSword() {
      this.name = 'Iron sword';
      this.hit = 90;
      this.might = 5;
      this.weight = 5;
      this.crit = 0;
      IronSword.__super__.constructor.call(this);
    }

    return IronSword;

  })(item.Sword);

  item.Lance = (function(_super) {
    __extends(Lance, _super);

    function Lance() {
      this.image = 'iron_lance.png';
      this.range = [1];
      Lance.__super__.constructor.call(this);
    }

    return Lance;

  })(item.Weapon);

  item.IronLance = (function(_super) {
    __extends(IronLance, _super);

    function IronLance() {
      this.name = 'Iron lance';
      this.hit = 80;
      this.might = 7;
      this.weight = 8;
      this.crit = 0;
      IronLance.__super__.constructor.call(this);
    }

    return IronLance;

  })(item.Lance);

  item.Axe = (function(_super) {
    __extends(Axe, _super);

    function Axe() {
      this.image = 'iron_axe.png';
      this.range = [1];
      Axe.__super__.constructor.call(this);
    }

    return Axe;

  })(item.Weapon);

  item.IronAxe = (function(_super) {
    __extends(IronAxe, _super);

    function IronAxe() {
      this.name = 'Iron axe';
      this.hit = 75;
      this.might = 8;
      this.weight = 10;
      this.crit = 0;
      IronAxe.__super__.constructor.call(this);
    }

    return IronAxe;

  })(item.Axe);

  item.Bow = (function(_super) {
    __extends(Bow, _super);

    function Bow() {
      this.image = 'iron_bow.png';
      this.range = [2];
      Bow.__super__.constructor.call(this);
    }

    return Bow;

  })(item.Weapon);

  item.IronBow = (function(_super) {
    __extends(IronBow, _super);

    function IronBow() {
      this.name = 'Iron bow';
      this.hit = 85;
      this.might = 6;
      this.weight = 5;
      this.crit = 0;
      IronBow.__super__.constructor.call(this);
    }

    return IronBow;

  })(item.Bow);

}).call(this);
