// Generated by CoffeeScript 1.7.1
(function() {
  _vn.Scene = (function() {
    function Scene(ui) {
      this.ui = ui;
      this.wrapper = this.ui.vn.wrapper.find('.scene');
    }

    Scene.prototype.init = function(bgImage, lines) {};

    return Scene;

  })();

}).call(this);
