// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.uclass = {
    special: {}
  };

  window.uclass.Mercenary = (function(_super) {
    __extends(Mercenary, _super);

    function Mercenary(attr) {
      this.uclassName = 'Mercenary';
      this.wield = [item.Sword];
      this.baseStats = {
        baseHp: 18,
        move: 5,
        str: 3,
        def: 2,
        skill: 3,
        speed: 3,
        res: 1,
        luck: 2,
        aid: 7,
        con: 5,
        mag: 0
      };
      this.growthRates = {
        baseHp: .8,
        str: .5,
        skill: .35,
        speed: .35,
        luck: .1,
        def: .25,
        res: .15
      };
      Mercenary.__super__.constructor.call(this, attr);
    }

    return Mercenary;

  })(Unit);

  window.uclass.Archer = (function(_super) {
    __extends(Archer, _super);

    function Archer(attr) {
      this.uclassName = 'Archer';
      this.wield = [item.Bow];
      this.baseStats = {
        baseHp: 18,
        move: 5,
        str: 4,
        def: 2,
        skill: 5,
        speed: 6,
        res: 1,
        luck: 2,
        aid: 7,
        con: 5,
        mag: 0
      };
      this.growthRates = {
        baseHp: .65,
        str: .4,
        skill: .45,
        speed: .40,
        luck: .1,
        def: .25,
        res: .15
      };
      Archer.__super__.constructor.call(this, attr);
    }

    return Archer;

  })(Unit);

  window.uclass.special.Ace = (function(_super) {
    __extends(Ace, _super);

    function Ace() {
      var attr;
      attr = {
        name: 'Ace',
        baseHp: 22,
        baseMp: 5,
        move: 4,
        str: 7,
        def: 3,
        skill: 4,
        speed: 4,
        res: 2,
        luck: 8,
        aid: 7,
        con: 5,
        mag: 0,
        level: 1,
        picture: true,
        lord: true,
        inventory: [new item.IronSword()]
      };
      Ace.__super__.constructor.call(this, attr);
    }

    return Ace;

  })(uclass.Mercenary);

  window.uclass.special.Arrow = (function(_super) {
    __extends(Arrow, _super);

    function Arrow() {
      var attr;
      attr = {
        name: 'Arrow',
        baseHp: 18,
        baseMp: 5,
        move: 4,
        str: 5,
        def: 4,
        skill: 5,
        speed: 6,
        res: 2,
        luck: 5,
        aid: 7,
        con: 5,
        mag: 0,
        level: 1,
        picture: true,
        inventory: [new item.IronBow()]
      };
      attr.inventory.push(new item.IronBow());
      Arrow.__super__.constructor.call(this, attr);
    }

    return Arrow;

  })(uclass.Archer);

  window.uclass.special.Luciana = (function(_super) {
    __extends(Luciana, _super);

    function Luciana() {
      var attr;
      attr = {
        name: 'Luciana',
        baseHp: 22,
        baseMp: 5,
        move: 4,
        str: 7,
        def: 3,
        skill: 4,
        speed: 4,
        res: 2,
        luck: 8,
        aid: 7,
        con: 5,
        mag: 0,
        level: 1,
        inventory: [new item.IronSword()]
      };
      Luciana.__super__.constructor.call(this, attr);
    }

    return Luciana;

  })(uclass.Mercenary);

  window.uclass.special.Kenji = (function(_super) {
    __extends(Kenji, _super);

    function Kenji() {
      var attr;
      attr = {
        name: 'Kenji',
        baseHp: 22,
        baseMp: 5,
        move: 4,
        str: 7,
        def: 3,
        skill: 4,
        speed: 4,
        res: 2,
        luck: 8,
        aid: 7,
        con: 5,
        mag: 0,
        level: 1,
        inventory: [new item.IronSword()]
      };
      Kenji.__super__.constructor.call(this, attr);
    }

    return Kenji;

  })(uclass.Mercenary);

}).call(this);
