// Generated by CoffeeScript 1.7.1
(function() {
  window.UnitAction = (function() {
    function UnitAction(ui, unit) {
      this.ui = ui;
      this.unit = unit;
    }

    UnitAction.prototype.doAction = function(action, callback) {
      var afterDelay, afterFadeIn, boxEl, css, left0, tw;
      this.action = action;
      this.callback = callback;
      this.container = $('<div></div>');
      this.container.addClass('unit-action-container').appendTo('.canvas-container');
      boxEl = $('.sidebar .unit-info').clone().addClass('blue-box');
      this.container.append(boxEl);
      this.box = new UnitInfoBox(this.ui, boxEl);
      this.box.init(this.unit, false, false);
      this.box.show();
      tw = this.ui.tw;
      left0 = (this.unit.pos.j + .5) * tw - this.ui.origin.j;
      css = {};
      css.left = left0 - boxEl.width() / 2;
      css.top = (this.unit.pos.i + 1) * tw + 5 - this.ui.origin.i;
      this.container.css(css);
      if (this.action instanceof skill.Skill) {
        this.message = this.action.getMessageEl();
        this.message.addClass('blue-box').appendTo(this.container);
      }
      afterFadeIn = (function(_this) {
        return function() {
          setTimeout(afterDelay, _this.delay * 4);
          if (_this.action instanceof skill.Skill) {
            _this.unit.mp -= _this.action.mp;
            return _this.box.init(_this.unit, true, false);
          }
        };
      })(this);
      afterDelay = (function(_this) {
        return function() {
          _this.container.fadeOut(_this.delay);
          return _this.message.fadeOut(_this.delay, _this.callback);
        };
      })(this);
      this.delay = 600;
      return this.message.fadeIn(this.delay, afterFadeIn);
    };

    return UnitAction;

  })();

}).call(this);
