// Generated by CoffeeScript 1.12.2
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window._enemy = {};

  _enemy.Mercenary = (function(superClass) {
    extend(Mercenary, superClass);

    function Mercenary(attr) {
      if (!('items' in attr)) {
        attr.items = [new _item.IronSword()];
      }
      Mercenary.__super__.constructor.call(this, attr);
    }

    return Mercenary;

  })(_uclass.Mercenary);

  _enemy.Soldier = (function(superClass) {
    extend(Soldier, superClass);

    function Soldier(attr) {
      if (!('items' in attr)) {
        attr.items = [new _item.IronLance()];
      }
      Soldier.__super__.constructor.call(this, attr);
    }

    return Soldier;

  })(_uclass.Soldier);

  _enemy.Fighter = (function(superClass) {
    extend(Fighter, superClass);

    function Fighter(attr) {
      if (!('items' in attr)) {
        attr.items = [new _item.IronAxe()];
      }
      Fighter.__super__.constructor.call(this, attr);
    }

    return Fighter;

  })(_uclass.Fighter);

  _enemy.Archer = (function(superClass) {
    extend(Archer, superClass);

    function Archer(attr) {
      if (!('items' in attr)) {
        attr.items = [new _item.IronBow()];
      }
      Archer.__super__.constructor.call(this, attr);
    }

    return Archer;

  })(_uclass.Archer);

}).call(this);
