// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window._enemy = {};

  _enemy.Mercenary = (function(_super) {
    __extends(Mercenary, _super);

    function Mercenary(attr) {
      if (!('items' in attr)) {
        attr.items = [new _item.IronSword()];
      }
      Mercenary.__super__.constructor.call(this, attr);
    }

    return Mercenary;

  })(_uclass.Mercenary);

  _enemy.Soldier = (function(_super) {
    __extends(Soldier, _super);

    function Soldier(attr) {
      if (!('items' in attr)) {
        attr.items = [new _item.IronLance()];
      }
      Soldier.__super__.constructor.call(this, attr);
    }

    return Soldier;

  })(_uclass.Soldier);

  _enemy.Fighter = (function(_super) {
    __extends(Fighter, _super);

    function Fighter(attr) {
      if (!('items' in attr)) {
        attr.items = [new _item.IronAxe()];
      }
      Fighter.__super__.constructor.call(this, attr);
    }

    return Fighter;

  })(_uclass.Fighter);

  _enemy.Archer = (function(_super) {
    __extends(Archer, _super);

    function Archer(attr) {
      if (!('items' in attr)) {
        attr.items = [new _item.IronBow()];
      }
      Archer.__super__.constructor.call(this, attr);
    }

    return Archer;

  })(_uclass.Archer);

}).call(this);
