// Generated by CoffeeScript 1.12.2
(function() {
  _unit.Inventory = (function() {
    Inventory.MAX_SIZE = 5;

    function Inventory(unit1, items1) {
      this.unit = unit1;
      this.items = items1;
      this.refresh();
    }

    Inventory.prototype.set = function(i, item) {
      this.items[i] = item;
      return this.refresh();
    };

    Inventory.prototype.prepend = function(item) {
      return this.items = [item].concat(this.items);
    };

    Inventory.prototype.push = function(item) {
      return this.items.push(item);
    };

    Inventory.prototype.get = function(i) {
      return this.items[i];
    };

    Inventory.prototype.it = function() {
      return this.items.slice(0, this.items.length);
    };

    Inventory.prototype.size = function() {
      return this.items.length;
    };

    Inventory.prototype.remove = function(arg) {
      var i;
      if (arg instanceof _item.Item) {
        i = this.items.indexOf(arg);
      } else {
        i = arg;
      }
      this.items.splice(i, 1);
      return this.refresh();
    };

    Inventory.prototype.setEquipped = function(item) {
      var i;
      i = this.items.indexOf(item);
      this.items.splice(i, 1);
      this.items = [item].concat(this.items);
      return this.refresh();
    };

    Inventory.prototype.refresh = function() {
      var equippedSet, item, j, len, ref, totalRange;
      totalRange = new Range();
      equippedSet = false;
      ref = this.items;
      for (j = 0, len = ref.length; j < len; j++) {
        item = ref[j];
        if (this.unit.canWield(item)) {
          if (!equippedSet) {
            this.unit.equipped = item;
            equippedSet = true;
          }
          totalRange = totalRange.union(item.range);
        }
      }
      this.unit.totalRange = totalRange;
      if (!equippedSet) {
        this.unit.equipped = null;
      }
      return this.unit.calcCombatStats();
    };

    Inventory.prototype.pickle = function() {
      var array, item, j, len, ref;
      array = [];
      ref = this.items;
      for (j = 0, len = ref.length; j < len; j++) {
        item = ref[j];
        array.push(item.pickle());
      }
      return array;
    };

    Inventory.unpickle = function(pickled, unit) {
      var item, items, j, len, pickledItem;
      if (pickled == null) {
        return null;
      }
      items = [];
      for (j = 0, len = pickled.length; j < len; j++) {
        pickledItem = pickled[j];
        item = _item.Item.unpickle(pickledItem);
        if (item === null) {
          return null;
        } else {
          items.push(item);
        }
      }
      return new _unit.Inventory(unit, items);
    };

    return Inventory;

  })();

}).call(this);
