// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _unit.special = {};

  _unit.special.Ace = (function(_super) {
    __extends(Ace, _super);

    function Ace() {
      this.name = 'Ace';
      this.level = 2;
      this.picture = true;
      this.items = [new _item.IronSword()];
      this.skills = [new _skill.Flare()];
      this.startStats = {
        maxHp: 30,
        maxMp: 10,
        str: 6,
        def: 4,
        skill: 3.8,
        speed: 5,
        res: 2,
        luck: 8,
        mag: 3
      };
      this.growthRates = {
        maxHp: .7,
        maxMp: 1,
        str: .5,
        skill: .35,
        speed: .35,
        luck: .5,
        def: .4,
        res: .15,
        mag: .3
      };
      Ace.__super__.constructor.call(this);
    }

    return Ace;

  })(_uclass.Mercenary);

  _unit.special.Arrow = (function(_super) {
    __extends(Arrow, _super);

    function Arrow() {
      this.name = 'Arrow';
      this.level = 1;
      this.picture = true;
      this.items = [new _item.IronBow()];
      this.skills = [new _skill.FirstAid()];
      this.startStats = {
        maxHp: 24,
        maxMp: 10,
        str: 4,
        def: 4,
        skill: 4.0,
        speed: 4.1,
        res: 2,
        luck: 2,
        mag: 2
      };
      this.growthRates = {
        maxHp: .65,
        maxMp: 1,
        str: .4,
        skill: .45,
        speed: .45,
        luck: .6,
        def: .25,
        res: .15,
        mag: .4
      };
      Arrow.__super__.constructor.call(this);
    }

    return Arrow;

  })(_uclass.Archer);

  _unit.special.Luciana = (function(_super) {
    __extends(Luciana, _super);

    function Luciana() {
      this.name = 'Luciana';
      this.level = 3;
      this.picture = true;
      this.items = [new _item.IronLance()];
      this.skills = [new _skill.Protect()];
      this.startStats = {
        maxHp: 28,
        maxMp: 10,
        str: 3.5,
        def: 6,
        skill: 3.8,
        speed: 3.2,
        res: 2,
        luck: 4,
        mag: 0
      };
      this.growthRates = {
        maxHp: .8,
        maxMp: 1,
        str: .4,
        skill: .35,
        speed: .35,
        luck: .3,
        def: .5,
        res: .15
      };
      Luciana.__super__.constructor.call(this);
    }

    return Luciana;

  })(_uclass.Soldier);

  _unit.special.Kenji = (function(_super) {
    __extends(Kenji, _super);

    function Kenji() {
      this.name = 'Kenji';
      this.level = 2;
      this.picture = true;
      this.items = [new _item.IronAxe()];
      this.skills = [new _skill.Temper()];
      this.startStats = {
        maxHp: 36,
        maxMp: 10,
        str: 7,
        def: 3.5,
        skill: 4,
        speed: 5,
        res: 2,
        luck: 4,
        mag: 0
      };
      this.growthRates = {
        maxHp: .8,
        maxMp: 1,
        str: .5,
        skill: .35,
        speed: .35,
        luck: .45,
        def: .35,
        res: .15
      };
      Kenji.__super__.constructor.call(this);
    }

    return Kenji;

  })(_uclass.Fighter);

  _unit.special.Shiina = (function(_super) {
    __extends(Shiina, _super);

    function Shiina() {
      this.name = 'Shiina';
      this.level = 2;
      this.picture = true;
      this.items = [];
      this.skills = [];
      this.startStats = {
        maxHp: 30,
        maxMp: 10,
        str: 60,
        def: 4,
        skill: 3.8,
        speed: 50,
        res: 2,
        luck: 8,
        mag: 3
      };
      this.growthRates = {
        maxHp: .7,
        maxMp: 1,
        str: .5,
        skill: .35,
        speed: .35,
        luck: .5,
        def: .4,
        res: .15,
        mag: .3
      };
      Shiina.__super__.constructor.call(this);
    }

    return Shiina;

  })(_uclass.Mercenary);

}).call(this);
