// Generated by CoffeeScript 1.12.2
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  _unit.special = {};

  _unit.special.Ace = (function(superClass) {
    extend(Ace, superClass);

    function Ace() {
      this.name = 'Ace';
      this.level = 2;
      this.picture = true;
      this.items = [new _item.IronSword()];
      this.allSkills = [
        {
          level: 1,
          skill: new _skill.Flare()
        }, {
          level: 3,
          skill: new _skill.SwordRain()
        }, {
          level: 5,
          skill: new _skill.Meteor()
        }
      ];
      this.startStats = {
        maxHp: 30,
        maxMp: 10,
        str: 4.2,
        def: 4,
        skill: 3.8,
        speed: 5,
        res: 2,
        luck: 4,
        mag: 3
      };
      this.growthRates = {
        maxHp: .7,
        maxMp: 1,
        str: .5,
        skill: .35,
        speed: .35,
        luck: .5,
        def: .4,
        res: .15,
        mag: .3
      };
      Ace.__super__.constructor.call(this);
    }

    return Ace;

  })(_uclass.Mercenary);

  _unit.special.Arrow = (function(superClass) {
    extend(Arrow, superClass);

    function Arrow() {
      this.name = 'Arrow';
      this.level = 1;
      this.picture = true;
      this.items = [new _item.IronBow()];
      this.allSkills = [
        {
          level: 1,
          skill: new _skill.FirstAid()
        }, {
          level: 3,
          skill: new _skill.PoisonArrow()
        }, {
          level: 5,
          skill: new _skill.ThrowingKnives()
        }
      ];
      this.startStats = {
        maxHp: 24,
        maxMp: 10,
        str: .4,
        def: 4,
        skill: 4.0,
        speed: 4.1,
        res: 2,
        luck: 2,
        mag: 2
      };
      this.growthRates = {
        maxHp: .65,
        maxMp: 1,
        str: .4,
        skill: .45,
        speed: .45,
        luck: .6,
        def: .25,
        res: .15,
        mag: .4
      };
      Arrow.__super__.constructor.call(this);
    }

    return Arrow;

  })(_uclass.Archer);

  _unit.special.Luciana = (function(superClass) {
    extend(Luciana, superClass);

    function Luciana() {
      this.name = 'Luciana';
      this.level = 2;
      this.picture = true;
      this.items = [new _item.IronLance()];
      this.allSkills = [
        {
          level: 1,
          skill: new _skill.Protect()
        }
      ];
      this.startStats = {
        maxHp: 28,
        maxMp: 10,
        str: 3.5,
        def: 6,
        skill: 3.8,
        speed: 3.2,
        res: 2,
        luck: 4,
        mag: 0
      };
      this.growthRates = {
        maxHp: .8,
        maxMp: 1,
        str: .4,
        skill: .35,
        speed: .35,
        luck: .3,
        def: .5,
        res: .15
      };
      Luciana.__super__.constructor.call(this);
    }

    return Luciana;

  })(_uclass.Soldier);

  _unit.special.Kenji = (function(superClass) {
    extend(Kenji, superClass);

    function Kenji() {
      this.name = 'Kenji';
      this.level = 2;
      this.picture = true;
      this.items = [new _item.IronAxe()];
      this.allSkills = [
        {
          level: 1,
          skill: new _skill.Temper()
        }
      ];
      this.startStats = {
        maxHp: 36,
        maxMp: 10,
        str: 7,
        def: 3.5,
        skill: 4,
        speed: 5,
        res: 2,
        luck: 4,
        mag: 0
      };
      this.growthRates = {
        maxHp: .8,
        maxMp: 1,
        str: .5,
        skill: .35,
        speed: .35,
        luck: .45,
        def: .35,
        res: .15
      };
      Kenji.__super__.constructor.call(this);
    }

    return Kenji;

  })(_uclass.Fighter);

  _unit.special.Shiina = (function(superClass) {
    extend(Shiina, superClass);

    function Shiina() {
      this.name = 'Shiina';
      this.level = 5;
      this.picture = true;
      this.items = [new _item.Shine()];
      this.allSkills = [
        {
          level: 1,
          skill: new _skill.Heal()
        }
      ];
      this.startStats = {
        maxHp: 26,
        maxMp: 10,
        str: 1,
        def: 2,
        skill: 4,
        speed: 4,
        res: 5,
        luck: 5,
        mag: 4
      };
      this.growthRates = {
        maxHp: .65,
        maxMp: 1,
        str: .1,
        skill: .45,
        speed: .45,
        luck: .6,
        def: .2,
        res: .5,
        mag: .55
      };
      Shiina.__super__.constructor.call(this);
    }

    return Shiina;

  })(_uclass.Monk);

}).call(this);
