// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window._team = {};

  _team.Team = (function() {
    function Team(units) {
      var unit, _i, _len, _ref;
      this.units = units;
      _ref = this.units;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        unit = _ref[_i];
        unit.setTeam(this);
      }
    }

    return Team;

  })();

  _team.PlayerTeam = (function(_super) {
    __extends(PlayerTeam, _super);

    function PlayerTeam(units, attr) {
      var unit, _i, _len, _ref;
      this.units = units;
      if (attr == null) {
        attr = {};
      }
      _ref = this.units;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        unit = _ref[_i];
        if (!('skills' in unit)) {
          unit.skills = [];
        }
        unit.skills = [new _skill.Defend()].concat(unit.skills);
      }
      PlayerTeam.__super__.constructor.call(this, this.units);
    }

    return PlayerTeam;

  })(_team.Team);

  _team.EnemyTeam = (function(_super) {
    __extends(EnemyTeam, _super);

    function EnemyTeam(units, attr) {
      var unit, _i, _len, _ref;
      this.units = units;
      if (attr == null) {
        attr = {};
      }
      _ref = this.units;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        unit = _ref[_i];
        if (!('aiType' in unit)) {
          unit.aiType = _unit.AI_TYPE.NORMAL;
        }
        if ('defaultName' in attr && (unit.name == null)) {
          unit.setName(attr.defaultName);
        }
      }
      EnemyTeam.__super__.constructor.call(this, this.units);
    }

    return EnemyTeam;

  })(_team.Team);

}).call(this);
