// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window._team = {};

  _team.Team = (function() {
    function Team(units) {
      var unit, _i, _len, _ref;
      this.units = units;
      _ref = this.units;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        unit = _ref[_i];
        unit.setTeam(this);
      }
    }

    Team.prototype.addUnit = function(unit) {
      this.units.push(unit);
      return unit.setTeam(this);
    };

    return Team;

  })();

  _team.PlayerTeam = (function(_super) {
    __extends(PlayerTeam, _super);

    function PlayerTeam(units) {
      var unit, _i, _len, _ref;
      this.units = units;
      _ref = this.units;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        unit = _ref[_i];
        this.initPlayerUnit(unit);
      }
      PlayerTeam.__super__.constructor.call(this, this.units);
    }

    PlayerTeam.prototype.addUnit = function(unit) {
      PlayerTeam.__super__.addUnit.call(this, unit);
      return this.initPlayerUnit(unit);
    };

    PlayerTeam.prototype.initPlayerUnit = function(unit) {
      return unit.allSkills = [
        {
          level: 1,
          skill: new _skill.Defend()
        }
      ].concat(unit.allSkills);
    };

    PlayerTeam.prototype.pickle = function() {
      var array, unit, _i, _len, _ref;
      array = [];
      _ref = this.units;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        unit = _ref[_i];
        array.push(unit.pickle());
      }
      return array;
    };

    PlayerTeam.unpickle = function(pickled) {
      var pickledUnit, unit, units, _i, _len;
      if (!pickled instanceof Array) {
        return null;
      }
      units = [];
      for (_i = 0, _len = pickled.length; _i < _len; _i++) {
        pickledUnit = pickled[_i];
        unit = _unit.Unit.unpickle(pickledUnit);
        if (unit === null) {
          return null;
        } else {
          units.push(unit);
        }
      }
      return new _team.PlayerTeam(units);
    };

    return PlayerTeam;

  })(_team.Team);

  _team.EnemyTeam = (function(_super) {
    __extends(EnemyTeam, _super);

    EnemyTeam.prototype.insigniaImagePath = 'images/bandit_insignia.png';

    function EnemyTeam(units, attr) {
      var dld, item, unit, _i, _j, _k, _len, _len1, _len2, _ref, _ref1, _ref2;
      this.units = units;
      if (attr == null) {
        attr = {};
      }
      if ('reinforcements' in attr) {
        this.reinforcements = attr.reinforcements;
      } else {
        this.reinforcements = [];
      }
      if (!('defaultAiType' in attr)) {
        attr.defaultAiType = _unit.aiType.normal;
      }
      _ref = this.reinforcements;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        unit = _ref[_i];
        unit.setTeam(this);
      }
      _ref1 = this.units.concat(this.reinforcements);
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        unit = _ref1[_j];
        if (!('aiType' in unit)) {
          unit.aiType = attr.defaultAiType;
        }
        if (!('aiOptions' in unit)) {
          unit.aiOptions = {};
        }
        if ('defaultName' in attr && (unit.name == null)) {
          unit.setName(attr.defaultName);
        }
        if ('defaultLevel' in attr && (unit.level == null)) {
          if (unit.dld != null) {
            dld = unit.dld;
          } else {
            dld = 0;
          }
          unit.level = attr.defaultLevel + dld;
          delete unit.dld;
        }
        _ref2 = unit.inventory.it();
        for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
          item = _ref2[_k];
          item.uses = null;
        }
        unit.calcStatsInitial();
      }
      EnemyTeam.__super__.constructor.call(this, this.units);
    }

    return EnemyTeam;

  })(_team.Team);

}).call(this);
