// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window._uclass = {
    special: {}
  };

  _uclass.Mercenary = (function(_super) {
    __extends(Mercenary, _super);

    function Mercenary(attr) {
      var startStats;
      this.uclassName = 'Mercenary';
      this.wield = [_item.Sword];
      startStats = {
        maxHp: 18,
        move: 5,
        str: 3,
        def: 2,
        skill: 4,
        speed: 4,
        res: 1,
        luck: 2,
        mag: 0
      };
      this.fillInStartStats(startStats);
      if (this.growthRates == null) {
        this.growthRates = {
          maxHp: .8,
          str: .5,
          skill: .35,
          speed: .35,
          luck: .1,
          def: .25,
          res: .15
        };
      }
      Mercenary.__super__.constructor.call(this, attr);
    }

    return Mercenary;

  })(_unit.Unit);

  _uclass.Archer = (function(_super) {
    __extends(Archer, _super);

    function Archer(attr) {
      var startStats;
      this.uclassName = 'Archer';
      this.wield = [_item.Bow];
      startStats = {
        maxHp: 16,
        move: 5,
        str: 2,
        def: 2,
        skill: 3,
        speed: 3,
        res: 1,
        luck: 2,
        mag: 0
      };
      this.fillInStartStats(startStats);
      if (this.growthRates == null) {
        this.growthRates = {
          maxHp: .65,
          str: .4,
          skill: .45,
          speed: .40,
          luck: .1,
          def: .25,
          res: .15
        };
      }
      Archer.__super__.constructor.call(this, attr);
    }

    return Archer;

  })(_unit.Unit);

  _uclass.Soldier = (function(_super) {
    __extends(Soldier, _super);

    function Soldier(attr) {
      var startStats;
      this.uclassName = 'Soldier';
      this.wield = [_item.Lance];
      startStats = {
        maxHp: 20,
        move: 5,
        str: 2,
        def: 4,
        skill: 2,
        speed: 2,
        res: 1,
        luck: 2,
        mag: 0
      };
      this.fillInStartStats(startStats);
      if (this.growthRates == null) {
        this.growthRates = {
          maxHp: .8,
          str: .5,
          skill: .35,
          speed: .35,
          luck: .1,
          def: .25,
          res: .15
        };
      }
      Soldier.__super__.constructor.call(this, attr);
    }

    return Soldier;

  })(_unit.Unit);

  _uclass.Fighter = (function(_super) {
    __extends(Fighter, _super);

    function Fighter(attr) {
      var startStats;
      this.uclassName = 'Fighter';
      this.wield = [_item.Axe];
      startStats = {
        maxHp: 23,
        move: 5,
        str: 3,
        def: 1,
        skill: 1,
        speed: 2,
        res: 1,
        luck: 2,
        mag: 0
      };
      this.fillInStartStats(startStats);
      if (this.growthRates == null) {
        this.growthRates = {
          maxHp: .8,
          str: .5,
          skill: .35,
          speed: .35,
          luck: .1,
          def: .25,
          res: .15
        };
      }
      Fighter.__super__.constructor.call(this, attr);
    }

    return Fighter;

  })(_unit.Unit);

}).call(this);
