// Generated by CoffeeScript 1.8.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _file.fs.Chapter1 = (function(_super) {
    __extends(Chapter1, _super);

    function Chapter1(file) {
      this.file = file;
      this.scene2 = __bind(this.scene2, this);
      this.chapter = __bind(this.chapter, this);
      this.destroyVn = __bind(this.destroyVn, this);
      this.scene1 = __bind(this.scene1, this);
      this.chapterIntro = __bind(this.chapterIntro, this);
      this.chapterDisplay = __bind(this.chapterDisplay, this);
      Chapter1.__super__.constructor.call(this, this.file);
      this.chapterId = 1;
      this.chapterName = 'Hellhounds';
      this.nextFs = _file.fs.Chapter2;
    }

    Chapter1.prototype.init = function() {
      var lines;
      this.ui = new _vn.VisualNovelUI();
      lines = [['Eutruria was a large, peaceful kingdom. The Hadoka family had ruled since times long forgotten, maintaining order throughout the land.', 'The current king, Hitoyoshi, was benevolent and had rightfully earned the respect of his people. But as King Hitoyoshi’s health declined, a change in leadership was inevitable.', 'Legend has it that the Hadoka family heirloom, the Aqua Emblem, would recognize the true heir to the throne when the issue of succession arose.'], ['But the Hadokas viewed this legend for what it was: a legend. To them, the Aqua Emblem was just a blue gemstone. Its influence was purely symbolic.', 'When King Hitoyoshi died, his son Sanzu ascended to the throne. And that was when the Aqua Emblem made its decision...']];
      return this.ui.fullTextbox.init(lines, this.chapterDisplay);
    };

    Chapter1.prototype.chapterDisplay = function() {
      return this.ui.chapterDisplay.init(this.chapterId, this.chapterName, this.chapterIntro);
    };

    Chapter1.prototype.chapterIntro = function() {
      var lines;
      lines = [['In the forests far to the west of the Eutrurian capital, the mercenary group "Hellhounds" made its base.', 'The Hellhounds took on any work they could find. If the money was good, they fought without hesitation.', 'But their leader, Ace, dreamed of a higher purpose...']];
      return this.ui.fullTextbox.init(lines, this.scene1);
    };

    Chapter1.prototype.scene1 = function() {
      var lines;
      lines = [['ace', 'Listen up everybody, we have a job today.'], ['arrow', 'Finally something to do!'], ['ace', 'Bandits have been raiding Yaksasu village, and the villagers will pay us if we drive them out.'], ['luciana', 'I\'ve heard about this. They have a fort on Yaksasu ridge. Sneaking up on them will be nearly impossible...'], ['ace', 'Exactly. Arrow, Kenji: be careful on this one. I know it’s been a long time since Hitomi died, but... I can’t let that happen again.'], ['arrow', 'We hear you, Ace. Don\'t worry. We\'re stronger than we were back then.'], ['luciana', 'Yeah, Arrow\'s right.'], ['ace', 'Kenji, anything to add?'], ['kenji', 'Huh? What are we talking about? But yes! That\'s a great idea, boss!'], ['ace', 'Uh... I didn\'t suggest anything.'], ['kenji', 'Okay, fine, whatever. Let\'s go out to play with those bandits! It’ll be fun!! =D'], ['ace', 'And you wonder why I worry about your safety... -.-'], ['arrow', 'Anyway, shouldn\'t we be heading out?'], ['luciana', 'Yeah. Let\'s go.']];
      this.ui.scene.locationText = 'Hellhounds HQ';
      return this.ui.scene.init(lines, 'hellhounds_hq', this.destroyVn);
    };

    Chapter1.prototype.destroyVn = function() {
      return this.ui.destroy(this.chapter);
    };

    Chapter1.prototype.chapter = function() {
      this.ui = new _cui.ChapterUI(this.file);
      this.ui.setChapter(_chapters.Chapter1);
      return this.ui.startChapter(this.scene2);
    };

    Chapter1.prototype.scene2 = function() {
      var lines;
      this.ui = new _vn.VisualNovelUI();
      lines = [['luciana', 'Now that wasn\'t too hard, was it?'], ['arrow', 'Yeah! We showed them!'], ['kenji', 'w00t!'], ['ace', 'Yeah, I\'m glad we\'re okay. Personally, I\'m exhausted, so let\'s return to HQ.']];
      return this.ui.scene.init(lines, 'forest', this.chapterComplete);
    };

    return Chapter1;

  })(_file.FileState);

}).call(this);
