// Generated by CoffeeScript 1.8.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _file.fs.Chapter2 = (function(_super) {
    __extends(Chapter2, _super);

    function Chapter2(file) {
      this.file = file;
      this.victoryScene = __bind(this.victoryScene, this);
      this.deathScene = __bind(this.deathScene, this);
      this.chapter = __bind(this.chapter, this);
      this.destroyVn = __bind(this.destroyVn, this);
      this.chapterDisplay = __bind(this.chapterDisplay, this);
      this.init = __bind(this.init, this);
      Chapter2.__super__.constructor.call(this, this.file);
      this.chapterId = 2;
      this.chapterName = 'The red string of fate';
      this.nextFs = _file.fs.Chapter2;
    }

    Chapter2.prototype.init = function() {
      var lines;
      this.ui = new _vn.VisualNovelUI();
      lines = [['arrow', 'Stop. Do you hear that?'], ['luciana', 'Shhh. Hide here. There\'s a group of armed men coming.'], ['ace', 'More bandits? I thought we dealt with all of them.'], ['luciana', 'No... these aren\'t the small-time thieves that have been attacking Yaksasu village. They\'re professionals.'], ['ace', 'Damn... Best to stay here and let them pass.'], ['arrow', 'Do you see that? One of them is carrying a girl!'], ['ace', 'She\'s unconscious. We have to help her!'], ['kenji', 'Judging by her clothes, she looks like nobility! This one is gonna pay well... ;)'], ['ace', 'Shut up Kenji, there\'s no time for that.'], ['ace', 'HEY! What are you doing with that girl?'], ['morgan', 'It\'s none of your business, punk. Move it.'], ['ace', 'No. We won\'t let you pass!']];
      return this.ui.scene.init(lines, 'forest', this.chapterDisplay);
    };

    Chapter2.prototype.chapterDisplay = function() {
      return this.ui.chapterDisplay.init(this.chapterId, this.chapterName, this.destroyVn);
    };

    Chapter2.prototype.destroyVn = function() {
      return this.ui.destroy(this.chapter);
    };

    Chapter2.prototype.chapter = function() {
      this.ui = new _cui.ChapterUI(this.file);
      this.ui.setChapter(_chapters.Chapter2);
      return this.ui.startChapter(this.deathScene);
    };

    Chapter2.prototype.deathScene = function() {
      var lines;
      this.ui = new _vn.VisualNovelUI();
      lines = [['morgan', 'Kah... to think that I could lose to a group of nobodies like you guys... this was supposed to be an easy job......']];
      return this.ui.scene.init(lines, 'forest', this.victoryScene);
    };

    Chapter2.prototype.victoryScene = function() {
      var lines;
      lines = [['luciana', 'We did it... I can hardly believe it.'], ['ace', 'Yeah. The girl\'s over here. It looks likes she\'s still out of it. We\'ll take her with us.'], ['shiina', '... ungh ..... who are you?'], ['ace', 'I\'m Ace. You\'re safe now.']];
      return this.ui.scene.init(lines, 'forest', this.chapterComplete);
    };

    return Chapter2;

  })(_file.FileState);

}).call(this);
