// Generated by CoffeeScript 1.7.1
(function() {
  window._file = {};

  _file.fs = {};

  _file.difficulty = {
    normal: {
      statBonus: 1,
      expMultiplier: 4 / 3
    },
    hard: {
      statBonus: 0,
      expMultiplier: 1
    }
  };

  _file.File = (function() {
    function File() {}

    File.prototype.setFileState = function(fsCls) {
      return this.fileState = new fsCls(this);
    };

    File.prototype.init = function() {
      return this.fileState.init();
    };

    return File;

  })();

  _file.FileState = (function() {
    function FileState(file) {
      this.file = file;
    }

    return FileState;

  })();

}).call(this);
