// Generated by CoffeeScript 1.12.2
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  _chapterui.EndTurnMenu = (function() {
    function EndTurnMenu(ui) {
      this.ui = ui;
      this.menu = $('.end-turn');
    }

    EndTurnMenu.prototype.init = function() {
      var padding;
      padding = 5;
      this.menu.css(this.ui.centerElement(this.menu, padding));
      this.ui.controlState = new _cs.chapterui.EndTurnMenu(this.ui, this);
      return this.show();
    };

    EndTurnMenu.prototype.show = function() {
      this.ui.canvasOverlay.show();
      return this.menu.css('visibility', 'visible');
    };

    EndTurnMenu.prototype.hide = function() {
      this.ui.canvasOverlay.hide();
      return this.menu.css('visibility', 'hidden');
    };

    return EndTurnMenu;

  })();

  _cs.chapterui.EndTurnMenu = (function(superClass) {
    extend(EndTurnMenu, superClass);

    function EndTurnMenu(ui, menuObj) {
      this.ui = ui;
      this.menuObj = menuObj;
    }

    EndTurnMenu.prototype.f = function() {
      var ch;
      this.menuObj.hide();
      ch = this.ui.chapter;
      return ch.initTurn(ch.enemyTeam);
    };

    EndTurnMenu.prototype.d = function() {
      this.menuObj.hide();
      return this.ui.controlState = new _cs.chapterui.Map(this.ui);
    };

    return EndTurnMenu;

  })(_cs.chapterui.Chapter);

}).call(this);
