// Generated by CoffeeScript 1.12.2
(function() {
  _chapterui.TerrainBox = (function() {
    function TerrainBox(ui) {
      this.ui = ui;
      this.box = $('.terrain-box');
    }

    TerrainBox.prototype.init = function() {
      var defText, evadeText, terrain;
      terrain = this.ui.chapter.map.getTerrain(this.ui.cursor.pos);
      this.box.find('img').attr('src', terrain.image.src);
      this.box.find('.name').text(terrain.name);
      if (terrain.block) {
        evadeText = '--';
        defText = '--';
      } else {
        evadeText = terrain.evade;
        defText = terrain.def;
        if (evadeText > 0) {
          evadeText = '+' + evadeText;
        }
        if (defText > 0) {
          defText = '+' + defText;
        }
      }
      this.box.find('.evade').text(evadeText);
      this.box.find('.def').text(defText);
      return this.show();
    };

    TerrainBox.prototype.show = function() {
      return this.box.css('visibility', 'visible');
    };

    TerrainBox.prototype.hide = function() {
      return this.box.css('visibility', 'hidden');
    };

    return TerrainBox;

  })();

}).call(this);
