// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  _cs.cui.MapAbstract = (function(_super) {
    __extends(MapAbstract, _super);

    function MapAbstract() {
      return MapAbstract.__super__.constructor.apply(this, arguments);
    }

    MapAbstract.prototype.up = function() {
      if (this.ui.cursor.pos.i - 1 >= 0) {
        return this.ui.cursor.move(-1, 0);
      }
    };

    MapAbstract.prototype.down = function() {
      if (this.ui.cursor.pos.i + 1 < this.ui.chapter.map.height) {
        return this.ui.cursor.move(1, 0);
      }
    };

    MapAbstract.prototype.left = function() {
      if (this.ui.cursor.pos.j - 1 >= 0) {
        return this.ui.cursor.move(0, -1);
      }
    };

    MapAbstract.prototype.right = function() {
      if (this.ui.cursor.pos.j + 1 < this.ui.chapter.map.width) {
        return this.ui.cursor.move(0, 1);
      }
    };

    MapAbstract.prototype.s = function() {
      var unit;
      unit = this.ui.chapter.getUnitAt(this.ui.cursor.pos);
      if (unit != null) {
        return this.ui.unitInfoWindow.init(unit);
      }
    };

    MapAbstract.prototype.e = function() {
      return this.ui.endTurnMenu.init();
    };

    MapAbstract.prototype.moved = function() {
      return this.ui.terrainBox.init();
    };

    return MapAbstract;

  })(_cs.cui.Chapter);

  _cs.cui.Map = (function(_super) {
    __extends(Map, _super);

    function Map() {
      return Map.__super__.constructor.apply(this, arguments);
    }

    Map.prototype.f = function() {
      var pt, unit;
      pt = this.ui.chapter.playerTurn;
      if (pt.selectedUnit == null) {
        unit = this.ui.chapter.getUnitAt(this.ui.cursor.pos);
        if ((unit != null) && !unit.done) {
          return pt.select(unit);
        }
      } else if (pt.dest.pos.equals(this.ui.cursor.pos)) {
        return pt.initMove();
      }
    };

    Map.prototype.d = function() {
      return this.ui.chapter.playerTurn.deselect();
    };

    Map.prototype.e = function() {
      this.ui.chapter.playerTurn.deselect();
      return Map.__super__.e.call(this);
    };

    return Map;

  })(_cs.cui.MapAbstract);

  _cs.cui.EnemySelected = (function(_super) {
    __extends(EnemySelected, _super);

    function EnemySelected() {
      return EnemySelected.__super__.constructor.apply(this, arguments);
    }

    EnemySelected.prototype.f = function() {};

    EnemySelected.prototype.d = function() {
      EnemySelected.__super__.d.call(this);
      return this.ui.controlState = new _cs.cui.Map(this.ui);
    };

    return EnemySelected;

  })(_cs.cui.Map);

  _cs.cui.MapTarget = (function(_super) {
    __extends(MapTarget, _super);

    function MapTarget(ui, playerTurn) {
      this.ui = ui;
      this.playerTurn = playerTurn;
    }

    return MapTarget;

  })(_cs.cui.MapAbstract);

  _cs.cui.ChooseAttackTarget = (function(_super) {
    __extends(ChooseAttackTarget, _super);

    function ChooseAttackTarget() {
      return ChooseAttackTarget.__super__.constructor.apply(this, arguments);
    }

    ChooseAttackTarget.prototype.moved = function() {
      var target;
      ChooseAttackTarget.__super__.moved.call(this);
      target = this.ui.chapter.getUnitAt(this.ui.cursor.pos);
      if (target !== null && __indexOf.call(this.playerTurn.inAttackRange, target) >= 0) {
        this.playerTurn.battle = new _enc.Battle(this.ui, this.playerTurn.selectedUnit, target);
        return this.ui.battleStatsPanel.init(this.playerTurn.battle);
      } else {
        this.playerTurn.battle = null;
        return this.ui.battleStatsPanel.hide();
      }
    };

    ChooseAttackTarget.prototype.f = function() {
      if (this.playerTurn.battle != null) {
        this.ui.cursor.visible = false;
        this.ui.chapter.map.clearOverlay();
        this.ui.battleStatsPanel.hide();
        this.ui.unitInfoBox.hide();
        this.ui.terrainBox.hide();
        this.playerTurn.battle.doEncounter(this.playerTurn.afterBattle);
        return this.ui.controlState = new _cs.cui.Chapter(this.ui);
      }
    };

    ChooseAttackTarget.prototype.d = function() {
      this.ui.actionMenu.show();
      this.playerTurn.battle = null;
      this.ui.battleStatsPanel.hide();
      this.ui.cursor.moveTo(this.playerTurn.selectedUnit.pos);
      return this.ui.controlState = new _cs.cui.ActionMenu(this.ui, this.ui.actionMenu);
    };

    return ChooseAttackTarget;

  })(_cs.cui.MapTarget);

  _cs.cui.ChooseTradeTarget = (function(_super) {
    __extends(ChooseTradeTarget, _super);

    function ChooseTradeTarget() {
      return ChooseTradeTarget.__super__.constructor.apply(this, arguments);
    }

    ChooseTradeTarget.prototype.f = function() {
      var callback, target;
      callback = (function(_this) {
        return function(tradeMade) {
          if (tradeMade) {
            _this.playerTurn.selectedUnit.setDone();
            _this.playerTurn.deselect();
            return _this.ui.controlState = new _cs.cui.Map(_this.ui);
          }
        };
      })(this);
      target = this.ui.chapter.getUnitAt(this.ui.cursor.pos);
      if (target !== null && __indexOf.call(this.playerTurn.inTradeRange, target) >= 0) {
        return this.ui.tradeWindow.init(this.playerTurn.selectedUnit, target, callback);
      }
    };

    ChooseTradeTarget.prototype.d = function() {
      this.ui.actionMenu.init(this.playerTurn.selectedUnit);
      this.ui.cursor.moveTo(this.playerTurn.selectedUnit.pos);
      return this.ui.controlState = new _cs.cui.ActionMenu(this.ui, this.ui.actionMenu);
    };

    return ChooseTradeTarget;

  })(_cs.cui.MapTarget);

}).call(this);
