// Generated by CoffeeScript 1.12.2
(function() {
  window.Position = (function() {
    function Position(i, j) {
      this.i = i;
      this.j = j;
    }

    Position.prototype.clone = function() {
      return new Position(this.i, this.j);
    };

    Position.prototype.equals = function(pos) {
      return this.i === pos.i && this.j === pos.j;
    };

    Position.prototype.add = function(pos) {
      return new Position(this.i + pos.i, this.j + pos.j);
    };

    Position.prototype.subtract = function(pos) {
      return new Position(this.i - pos.i, this.j - pos.j);
    };

    Position.prototype.scale = function(alpha) {
      return new Position(alpha * this.i, alpha * this.j);
    };

    Position.prototype.distance = function(pos) {
      return Math.abs(this.i - pos.i) + Math.abs(this.j - pos.j);
    };

    Position.prototype.dot = function(pos) {
      return this.i * pos.i + this.j * pos.j;
    };

    Position.prototype.norm = function() {
      return Math.sqrt(this.i * this.i + this.j * this.j);
    };

    Position.prototype.toUnitVector = function() {
      return this.scale(1 / this.norm());
    };

    return Position;

  })();

}).call(this);
