// Generated by CoffeeScript 1.12.2
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window._terrain = {};

  _terrain.Terrain = (function() {
    function Terrain(name) {
      this.evade = 0;
      this.def = 0;
      this.block = false;
      this.image = new Image();
      this.image.src = "images/terrain/" + name + ".png";
    }

    return Terrain;

  })();

  _terrain.Plain = (function(superClass) {
    extend(Plain, superClass);

    function Plain() {
      Plain.__super__.constructor.call(this, 'plain');
      this.name = 'Plain';
    }

    return Plain;

  })(_terrain.Terrain);

  _terrain.Rocks = (function(superClass) {
    extend(Rocks, superClass);

    function Rocks() {
      Rocks.__super__.constructor.call(this, 'rocks');
      this.name = 'Rocks';
      this.block = true;
    }

    return Rocks;

  })(_terrain.Terrain);

  _terrain.Forest = (function(superClass) {
    extend(Forest, superClass);

    function Forest() {
      Forest.__super__.constructor.call(this, 'forest');
      this.name = 'Forest';
      this.evade = 20;
      this.def = 1;
    }

    return Forest;

  })(_terrain.Terrain);

  _terrain.River = (function(superClass) {
    extend(River, superClass);

    function River() {
      River.__super__.constructor.call(this, 'river');
      this.name = 'River';
      this.block = true;
    }

    return River;

  })(_terrain.Terrain);

  _terrain.Bridge = (function(superClass) {
    extend(Bridge, superClass);

    function Bridge() {
      Bridge.__super__.constructor.call(this, 'bridge');
      this.name = 'Bridge';
    }

    return Bridge;

  })(_terrain.Terrain);

  _terrain.Fort = (function(superClass) {
    extend(Fort, superClass);

    function Fort() {
      Fort.__super__.constructor.call(this, 'fort');
      this.name = 'Fort';
      this.evade = 30;
      this.def = 2;
    }

    return Fort;

  })(_terrain.Terrain);

}).call(this);
