// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window._terrain = {};

  _terrain.Terrain = (function() {
    function Terrain(name) {
      this.evade = 0;
      this.def = 0;
      this.block = false;
      this.image = new Image();
      this.image.src = "images/terrain/" + name + ".png";
    }

    return Terrain;

  })();

  _terrain.Plain = (function(_super) {
    __extends(Plain, _super);

    function Plain() {
      Plain.__super__.constructor.call(this, 'plain');
      this.name = 'Plain';
    }

    return Plain;

  })(_terrain.Terrain);

  _terrain.Rocks = (function(_super) {
    __extends(Rocks, _super);

    function Rocks() {
      Rocks.__super__.constructor.call(this, 'rocks');
      this.name = 'Rocks';
      this.block = true;
    }

    return Rocks;

  })(_terrain.Terrain);

  _terrain.Forest = (function(_super) {
    __extends(Forest, _super);

    function Forest() {
      Forest.__super__.constructor.call(this, 'forest');
      this.name = 'Forest';
      this.evade = 20;
      this.def = 1;
    }

    return Forest;

  })(_terrain.Terrain);

}).call(this);
